/*
*                 IFS Research & Development
*
*  This program is protected by copyright law and by international
*  conventions. All licensing, renting, lending or copying (including
*  for private use), and all other use of the program, which is not
*  expressively permitted by IFS Research & Development (IFS), is a
*  violation of the rights of IFS. Such violations will be reported to the
*  appropriate authorities.
*
*  VIOLATIONS OF ANY COPYRIGHT IS PUNISHABLE BY LAW AND CAN LEAD
*  TO UP TO TWO YEARS OF IMPRISONMENT AND LIABILITY TO PAY DAMAGES.
* ----------------------------------------------------------------------------
* File                          :
* Description                   :
* Notes                         :
* Other Programs Called :
* ----------------------------------------------------------------------------
* Modified    : Automatically generated by IFS/Design
* ----------------------------------------------------------------------------
*/

//-----------------------------------------------------------------------------
//-----------------------------   Package def  ------------------------------
//-----------------------------------------------------------------------------

package ifs.bidmaw;
//-----------------------------------------------------------------------------
//-----------------------------   Import def  ------------------------------
//-----------------------------------------------------------------------------

import ifs.fnd.asp.*;
import ifs.fnd.buffer.*;
import ifs.fnd.service.*;
import ifs.fnd.*;

//-----------------------------------------------------------------------------
//-----------------------------   Class def  ------------------------------
//-----------------------------------------------------------------------------

public class BidMatPurchLineDlg extends ASPPageProvider
{

   //-----------------------------------------------------------------------------
   //---------- Static constants ------------------------------------------------
   //-----------------------------------------------------------------------------

   public static boolean DEBUG = Util.isDebugEnabled("ifs.bidmaw.BidMatPurchLineDlg");

   //-----------------------------------------------------------------------------
   //---------- Header Instances created on page creation --------
   //-----------------------------------------------------------------------------

   private ASPBlock headblk;
   private ASPRowSet headset;
   private ASPCommandBar headbar;
   private ASPTable headtbl;
   private ASPBlockLayout headlay;
   
   private ASPManager mgr;
   private ASPQuery q;
   private ASPContext ctx;

   //-----------------------------------------------------------------------------
   //------------------------  Construction  ---------------------------
   //-----------------------------------------------------------------------------

   public  BidMatPurchLineDlg (ASPManager mgr, String page_path)
   {
      super(mgr,page_path);
   }

   public void run()
   {
      ASPManager mgr = getASPManager();
      if (mgr.dataTransfered())
         storeParamters();
      if( mgr.commandBarActivated() )
         eval(mgr.commandBarFunction());
      else if(mgr.dataTransfered())
         okFind();
      else if (mgr.buttonPressed("SUBMIT")) 
         submitCondition();
      else 
         okFind();
      adjust();
   }
   
   public void storeParamters() 
   {
      ASPManager mgr = getASPManager();

      if (mgr.dataTransfered())
      {
         ASPContext ctx = mgr.getASPContext();
         ASPBuffer buf = mgr.getTransferedData();
         String proj_no = buf.getValue("DATA/PROJ_NO");
         String purch_id = buf.getValue("DATA/PURCH_ID");
         if (!mgr.isEmpty(proj_no))
            ctx.setGlobal("PROJ_NO", proj_no);
         if (!mgr.isEmpty(purch_id))
            ctx.setGlobal("PURCH_ID", purch_id);
      }
   }
   
   //-----------------------------------------------------------------------------
   //------------------------  Command Bar functions  ---------------------------
   //-----------------------------------------------------------------------------

   public void okFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      ASPContext ctx = mgr.getASPContext();

      mgr.createSearchURL(headblk);
      q = trans.addQuery(headblk);
      q.addWhereCondition(" PROJ_NO = '"+ctx.findGlobal("PROJ_NO")+"' AND IS_PURCHED = 'FALSE' ");
      q.addWhereCondition("BID_MAT_REQ_API.GET_STATUS( PROJ_NO, REQ_ID)='2'");
      q.includeMeta("ALL");
//      if(mgr.dataTransfered())
//         q.addOrCondition(mgr.getTransferedData());
      mgr.querySubmit(trans,headblk);
      if (  headset.countRows() == 0 )
      {
         mgr.showAlert("BIDMATPURCHLINEDLGNODATA: No data found.");
         headset.clear();
      }
   }



   public void countFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      q = trans.addQuery(headblk);
      q.setSelectList("to_char(count(*)) N");
      mgr.submit(trans);
      headlay.setCountValue(toInt(headset.getValue("N")));
      headset.clear();
   }



   public void newRow()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPBuffer data;
      ASPCommand cmd;

      cmd = trans.addEmptyCommand("HEAD","BID_MAT_REQ_LINE_API.New__",headblk);
      cmd.setOption("ACTION","PREPARE");
      trans = mgr.perform(trans);
      data = trans.getBuffer("HEAD/DATA");
      headset.addRow(data);
   }


   //-----------------------------------------------------------------------------
   //------------------------  Predefines Head ---------------------------
   //-----------------------------------------------------------------------------

   public void  preDefine()
   {
      ASPManager mgr = getASPManager();

      headblk = mgr.newASPBlock("MAIN");
      headblk.addField("OBJID").
              setHidden();
      headblk.addField("OBJVERSION").
              setHidden();
      //Just for show
      headblk.addField("PROJ_NO").setLabel("BIDMATREQLINEPROJNO: Proj No"). setSize(20);
      headblk.addField("REQ_ID").setLabel("BIDMATREQLINEREQID: Req Id").setSize(20);
      headblk.addField("REQ_LINE_NO"). setLabel("BIDMATREQLINEREQLINENO: Req Line No").setSize(20);
      headblk.addField("MAT_NAME").setLabel("BIDMATREQLINEMATNAME: Mat Name").setSize(20);
      headblk.addField("SPECIFICATIONS").setLabel("BIDMATREQLINESPECIFICATIONS: Specifications").setSize(20);
      headblk.addField("REQ_QTY","Number").setLabel("BIDMATREQLINEREQQTY: Req Qty").setSize(20);
      headblk.addField("UNIT").setLabel("BIDMATREQLINEUNIT: Unit").setSize(20);
      headblk.addField("BUDGET_PRICE","Number").setLabel("BIDMATREQLINEBUDGETPRICE: Budget Price").setSize(20);
      headblk.addField("BUDGET_TOTAL_PRICE","Number").setLabel("BIDMATREQLINEBUDGETTOTALPRICE: Budget Total Price").setSize(20);
      headblk.addField("USED_PART").setLabel("BIDMATREQLINEUSEDPART: Used Part").setSize(20);
      headblk.addField("ACCEPT_TIME","Date").setLabel("BIDMATREQLINEACCEPTTIME: Accept Time").setSize(20);
      headblk.addField("BUDGET_LINE_NO").setLabel("BIDMATREQLINEBUDGETLINENO: Budget Line No").setSize(20);
      headblk.addField("CREATE_PERSON_NAME").
              setFunction("PERSON_INFO_API.GET_NAME (BID_MAT_REQ_API.GET_CREATE_PERSON( :PROJ_NO, :REQ_ID))").
              setLabel("BIDMATREQCREATEPERSONNAME: Create Person Name").
              setSize(30);
      headblk.addField("NOTE").setLabel("BIDMATREQLINENOTE: Note").setSize(20);
      headblk.addField("IS_PURCHED").setHidden().setLabel("BIDMATREQLINEISPURCHED: Is Purched").setSize(20);
      headblk.addField("PURCH_ID").setFunction("''").setSize(20).setHidden();
      
      headblk.setView("BID_MAT_REQ_LINE");
      headblk.defineCommand("BID_MAT_REQ_LINE_API","New__,Modify__,Remove__");
      headset = headblk.getASPRowSet();
      headbar = mgr.newASPCommandBar(headblk);
      headtbl = mgr.newASPTable(headblk);
      headtbl.setTitle("BIDMATPURCHLINEDLGTBLHEAD: Bid Mat Purch Lines Dlg");
      headtbl.enableRowSelect();
      headtbl.setWrap();
      headlay = headblk.getASPBlockLayout();
      headlay.setDefaultLayoutMode(headlay.MULTIROW_LAYOUT);
 



   }

   
   public void submitCondition(){
      
      mgr = getASPManager();
      ASPCommand cmdBuf; 
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ctx   = mgr.getASPContext();
     
      trans.clear();
      String standard_info = "";
      headset.storeSelections();  
      if (headlay.isSingleLayout())
         headset.selectRow();
      ASPBuffer selected_fields=headset.getSelectedRows("PROJ_NO,REQ_ID,REQ_LINE_NO");
      for(int i=0;i<selected_fields.countItems();i++){         
         ASPBuffer subBuff = selected_fields.getBufferAt(i);
         standard_info=standard_info + subBuff.getValueAt(0) + "^";    
         cmdBuf = trans.addCustomCommand("CREATECONDITION"+i, "BID_MAT_PURCH_LINE_API.Create_File");  
         cmdBuf.addParameter("PROJ_NO", subBuff.getValueAt(0));
         cmdBuf.addParameter("REQ_ID", subBuff.getValueAt(1));
         cmdBuf.addParameter("REQ_LINE_NO", subBuff.getValueAt(2));
         cmdBuf.addParameter("PURCH_ID",ctx.findGlobal("PURCH_ID"));
      }
      mgr.perform(trans);
   }



   public void  adjust()
   {
      // fill function body
      headbar.disableCommand(headbar.DELETE);
      headbar.disableCommand(headbar.EDITROW);
      headbar.disableCommand(headbar.NEWROW);
   }

   //-----------------------------------------------------------------------------
   //------------------------  Presentation functions  ---------------------------
   //-----------------------------------------------------------------------------

   protected String getDescription()
   {
      return "BIDMATPURCHLINEDLGDESC: Bid Mat Req Line";
   }


   protected String getTitle()
   {
      return "BIDMATPURCHLINEDLGTITLE: Bid Mat Req Line";
   }


   protected void printContents() throws FndException
   {
      ASPManager mgr = getASPManager();
      if (headlay.isVisible())
          appendToHTML(headlay.show());
      if (!headlay.isFindLayout() && headset.countRows() > 0)
      {
         beginDataPresentation();
         printSubmitButton("SUBMIT", mgr.translate("DOCCTWDOCISSUEDISTFILESDLGCREATE: 确定"), "OnClick='Close()'");
         printSpaces(1);
         printSubmitButton("CANCEL", mgr.translate("DOCCTWDOCISSUEDISTFILESDLGCANCEL: 取消"), "OnClick='javascript:window.close();'");
         endDataPresentation();
      }
    appendDirtyJavaScript("function Close()\n");
    appendDirtyJavaScript("{\n");
    appendDirtyJavaScript("   try\n");
    appendDirtyJavaScript("   {\n");
    appendDirtyJavaScript("      eval(\"opener.refreshParent()\");\n");
    appendDirtyJavaScript("   }\n");
    appendDirtyJavaScript("   catch(err){}\n");
    appendDirtyJavaScript("   try\n");
    appendDirtyJavaScript("   {\n");
    appendDirtyJavaScript("      window.close();\n");
    appendDirtyJavaScript("   }\n");
    appendDirtyJavaScript("   catch(err){}\n");
    appendDirtyJavaScript("}\n");

   }
}
