/*
*                 IFS Research & Development
*
*  This program is protected by copyright law and by international
*  conventions. All licensing, renting, lending or copying (including
*  for private use), and all other use of the program, which is not
*  expressively permitted by IFS Research & Development (IFS), is a
*  violation of the rights of IFS. Such violations will be reported to the
*  appropriate authorities.
*
*  VIOLATIONS OF ANY COPYRIGHT IS PUNISHABLE BY LAW AND CAN LEAD
*  TO UP TO TWO YEARS OF IMPRISONMENT AND LIABILITY TO PAY DAMAGES.
* ----------------------------------------------------------------------------
* File                          :
* Description                   :
* Notes                         :
* Other Programs Called :
* ----------------------------------------------------------------------------
* Modified    : Automatically generated by IFS/Design
* ----------------------------------------------------------------------------
*/

//-----------------------------------------------------------------------------
//-----------------------------   Package def  ------------------------------
//-----------------------------------------------------------------------------

package ifs.engmaw;
//-----------------------------------------------------------------------------
//-----------------------------   Import def  ------------------------------
//-----------------------------------------------------------------------------

import ifs.fnd.asp.*;
import ifs.fnd.buffer.*;
import ifs.fnd.service.*;
import ifs.fnd.*;
import ifs.genbaw.GenbawConstants;

//-----------------------------------------------------------------------------
//-----------------------------   Class def  ------------------------------
//-----------------------------------------------------------------------------

public class DrawingSendMan extends DrawingSend
{

   //-----------------------------------------------------------------------------
   //---------- Static constants ------------------------------------------------
   //-----------------------------------------------------------------------------

   public static boolean DEBUG = Util.isDebugEnabled("ifs.engmaw.DrawingSendMan");
   //-----------------------------------------------------------------------------
   //------------------------  Construction  ---------------------------
   //-----------------------------------------------------------------------------
   
   public  DrawingSendMan (ASPManager mgr, String page_path)
   {
      super(mgr,page_path);
   }
   
   public void okFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      mgr.createSearchURL(headblk);
      q = trans.addQuery(headblk);          
      q.includeMeta("ALL");
      if(mgr.dataTransfered())
         q.addOrCondition(mgr.getTransferedData());
      q.addWhereCondition("STATE_DB != 'Sended'");              
      mgr.querySubmit(trans,headblk);        
      if (  headset.countRows() == 0 )                           
      {
         mgr.showAlert("DRAWINGSENDNODATA: No data found.");
         headset.clear();
      }
      eval( drawing_send_line_set.syncItemSets() );
   }           
   
   public void  adjust()
   {
      // fill function body
      if(headlay.isSingleLayout()&&headset.countRows()>0){
         String state = headset.getValue("OBJSTATE");
//         if( ! ("Signed".equals(state))) 
//            headbar.disableCommand("Back");
         if( headlay.isSingleLayout() && ("Sended".equals(state))){ 
               headbar.disableCommand(headbar.DELETE);
               headbar.disableCommand(headbar.EDITROW);           
               drawing_send_line_bar.disableCommand( drawing_send_line_bar.DELETE );
               drawing_send_line_bar.disableCommand( drawing_send_line_bar.EDITROW );  
         }    
     }    
   }
   //-----------------------------------------------------------------------------
   //------------------------  Presentation functions  ---------------------------
   //-----------------------------------------------------------------------------

   protected String getDescription()
   {
      return "DRAWINGSENDMANDESC: Drawing Send Man";
   }


   protected String getTitle()
   {
//      return "DRAWINGSENDMANTITLE: Drawing Send Man";
      return getDescription();
   }

}
