/*
*                 IFS Research & Development
*
*  This program is protected by copyright law and by international
*  conventions. All licensing, renting, lending or copying (including
*  for private use), and all other use of the program, which is not
*  expressively permitted by IFS Research & Development (IFS), is a
*  violation of the rights of IFS. Such violations will be reported to the
*  appropriate authorities.
*
*  VIOLATIONS OF ANY COPYRIGHT IS PUNISHABLE BY LAW AND CAN LEAD
*  TO UP TO TWO YEARS OF IMPRISONMENT AND LIABILITY TO PAY DAMAGES.
* ----------------------------------------------------------------------------
* File                          :
* Description                   :
* Notes                         :
* Other Programs Called :
* ----------------------------------------------------------------------------
* Modified    : Automatically generated by IFS/Design
* ----------------------------------------------------------------------------
*/

//-----------------------------------------------------------------------------
//-----------------------------   Package def  ------------------------------
//-----------------------------------------------------------------------------

package ifs.engmaw;
//-----------------------------------------------------------------------------
//-----------------------------   Import def  ------------------------------
//-----------------------------------------------------------------------------

import ifs.fnd.asp.*;
import ifs.fnd.buffer.*;
import ifs.fnd.service.*;
import ifs.fnd.*;
import ifs.genbaw.GenbawConstants;

//-----------------------------------------------------------------------------
//-----------------------------   Class def  ------------------------------
//-----------------------------------------------------------------------------

public class DrawingListBackDlg extends ASPPageProvider
{

   //-----------------------------------------------------------------------------
   //---------- Static constants ------------------------------------------------
   //-----------------------------------------------------------------------------

   public static boolean DEBUG = Util.isDebugEnabled("ifs.engmaw.DrawingListBackDlg");

   //-----------------------------------------------------------------------------
   //---------- Header Instances created on page creation --------
   //-----------------------------------------------------------------------------
                          
   private ASPBlock headblk;
   private ASPRowSet headset;
   private ASPCommandBar headbar;
   private ASPTable headtbl;
   private ASPBlockLayout headlay;

   //-----------------------------------------------------------------------------
   //------------------------  Construction  ---------------------------
   //-----------------------------------------------------------------------------

   public  DrawingListBackDlg (ASPManager mgr, String page_path)
   {
      super(mgr,page_path);
   }
   
   protected String getDefProj() {
      ASPManager mgr = getASPManager();
      ASPContext ctx =mgr.getASPContext();
      return ctx.findGlobal(GenbawConstants.PERSON_DEFAULT_PROJECT);
   }         

   public void run()
   {
      ASPManager mgr = getASPManager();

      if( mgr.commandBarActivated() )
         eval(mgr.commandBarFunction());
      else if(mgr.dataTransfered())
         okFind();
      else if( !mgr.isEmpty(mgr.getQueryStringValue("SEARCH")) )
         okFind();
      else if (mgr.buttonPressed("SUBMIT")) {
         submitItem();  
      }
      else
         okFind();  
      adjust();
   }
   
   
   public void submitItem(){
      ASPManager mgr = getASPManager();
      ASPContext ctx =mgr.getASPContext();
       ASPCommand cmdBuf;       
       ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
       trans.clear();
       headset.storeSelections();  
       if (headlay.isSingleLayout())  
          headset.selectRow();
       ASPBuffer selected_fields=headset.getSelectedRows("BORROW_NO,BORROW_LINE_NO");
       for(int i=0;i<selected_fields.countItems();i++){         
           ASPBuffer subBuff = selected_fields.getBufferAt(i);
           cmdBuf = trans.addCustomCommand("CREATETREE"+i, "DRAWING_BACK_LINE_API.Create_Drawing_Back_Line");
           cmdBuf.addParameter("PROJ_NO", ctx.findGlobal("DRAWINGBACKLISTDLGPROJNO")); 
           cmdBuf.addParameter("BACK_NO", ctx.findGlobal("DRAWINGBACKLISTDLGID"));     
           cmdBuf.addParameter("BORROW_NO", subBuff.getValueAt(0));    
           cmdBuf.addParameter("BORROW_LINE_NO", subBuff.getValueAt(1));                       
       }
       trans=mgr.perform(trans);       
       trans.clear();      
    }    
   
   //-----------------------------------------------------------------------------
   //------------------------  Command Bar functions  ---------------------------
   //-----------------------------------------------------------------------------

   public void okFind()
   {
      ASPManager mgr = getASPManager();
      ASPContext ctx = mgr.getASPContext();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      trans.clear();  
      ASPQuery q;
      mgr.createSearchURL(headblk);
      q = trans.addQuery(headblk);
      q.addWhereCondition("SUPPLIER_ID = ?");      
      q.addWhereCondition("PROJ_NO = ?");      
      q.addParameter("SUPPLIER_ID", ctx.findGlobal("DRAWINGBACKLISTDLGSUPPLIERID"));
      q.addParameter("PROJ_NO", ctx.findGlobal("DRAWINGBACKLISTDLGPROJNO"));    
      q.addWhereCondition("VOLUME_NO NOT IN (SELECT VOLUME_NO FROM IFSAPP.DRAWING_BACK_LINE WHERE BACK_NO = '"+ctx.findGlobal("DRAWINGBACKLISTDLGID")+"' )");
      q.includeMeta("ALL");       
      if(mgr.dataTransfered())  
         q.addOrCondition(mgr.getTransferedData());
      mgr.querySubmit(trans,headblk);        
      if (  headset.countRows() == 0 )              
      {
         mgr.showAlert("DRAWINGLISTNODATA: No data found.");
         headset.clear();
      }
   }
    
   public void countFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      q = trans.addQuery(headblk);
      q.setSelectList("to_char(count(*)) N");
      mgr.submit(trans);
      headlay.setCountValue(toInt(headset.getValue("N")));
      headset.clear();
   }

   //-----------------------------------------------------------------------------
   //------------------------  Predefines Head ---------------------------
   //-----------------------------------------------------------------------------

   public void  preDefine()
   {
      ASPManager mgr = getASPManager();

      headblk = mgr.newASPBlock("MAIN");
      headblk.addField("OBJID").
              setHidden();
      headblk.addField("OBJVERSION").
              setHidden();
      headblk.addField("PROJ_NO").
              setInsertable().
              setMandatory().  
              setLabel("DRAWINGLISTBACKPROJECTNO: Project No").
              setDynamicLOV("GENERAL_PROJECT").
              setSize(20);
      headblk.addField("GENERAL_PROJECT_PROJ_DESC").
              setFunction("GENERAL_PROJECT_API.GET_PROJ_DESC (:PROJ_NO)").
              setLabel("DRAWINGLISTBACKPROJECTPROJDESC: General Project Proj Desc").
              setReadOnly().
              setSize(20);
      mgr.getASPField("PROJ_NO").setValidation("GENERAL_PROJECT_PROJ_DESC");
      headblk.addField("BORROW_NO").
              setLabel("DRAWINGLISTBACKBORROWNO");  
      headblk.addField("BORROW_LINE_NO").
              setLabel("DRAWINGLISTBACKBORROWLINENO");  
      headblk.addField("VOLUME_NO").
              setMandatory().
              setInsertable().
              setLabel("DRAWINGLISTBACKVOLUMENO: Volume No").
              setSize(20);
      headblk.addField("VOLUME_DESC").
              setInsertable().
              setLabel("DRAWINGLISTBACKVOLUMEDESC: Volume Desc").              
              setSize(120);   
      
      headblk.addField("MAJOR_NO").
              setInsertable().
              setDynamicLOV("VOLUME_MAJOR").
              setLabel("DRAWINGLISTBACKMAJORNO: Major No").
              setSize(20);
      headblk.addField("MAJOR_DESC").
              setReadOnly().
              setLabel("DRAWINGLISTBACKMAJORDESC: Major Desc").
              setSize(20);
      
      headblk.addField("COPIES","Number").
              setInsertable().
              setLabel("DRAWINGLISTBACKCOPIES: Copies").
              setSize(20);
      headblk.addField("SUPPLIER_ID").
              setInsertable().
              setLabel("DRAWINGLISTBACKSUPPLIERID: Supplier Id").
              setSize(20);
        
      headblk.addField("BACK_NO").
              setHidden().
              setFunction("''");  
         
      headblk.setView("DRAWING_BORROW_SUP");
//      headblk.defineCommand("DRAWING_LIST_API","New__,Modify__,Remove__");
      headset = headblk.getASPRowSet();
      headbar = mgr.newASPCommandBar(headblk);
      headtbl = mgr.newASPTable(headblk);
      headtbl.setTitle("DRAWINGLISTTBLHEAD: Drawing Lists");
      headtbl.enableRowSelect();
      headtbl.setWrap();
      headlay = headblk.getASPBlockLayout();
      headlay.setDefaultLayoutMode(headlay.MULTIROW_LAYOUT);
         
   }

   public void  adjust()
   {
      // fill function body
   }

   //-----------------------------------------------------------------------------
   //------------------------  Presentation functions  ---------------------------
   //-----------------------------------------------------------------------------

   protected String getDescription()
   {
      return "DRAWINGLISTDESC: Drawing List";
   }


   protected String getTitle()
   {
      return "DRAWINGLISTTITLE: Drawing List";
   }


   protected void printContents() throws FndException
   {
      ASPManager mgr = getASPManager();
      if (headlay.isVisible()){
          appendToHTML(headlay.show());
          beginDataPresentation();
          printSubmitButton("SUBMIT", mgr.translate("DOCCTWDOCISSUEDISTFILESDLGCREATE: 确定"), "OnClick='Close()'");
          printSpaces(1);
          printSubmitButton("CANCEL", mgr.translate("DOCCTWDOCISSUEDISTFILESDLGCANCEL: 取消"), "OnClick='javascript:window.close();'");
          endDataPresentation();
          appendDirtyJavaScript("function Close()\n");
          appendDirtyJavaScript("{\n");
          appendDirtyJavaScript("   try\n");
          appendDirtyJavaScript("   {\n");    
          appendDirtyJavaScript("      eval(\"opener.refreshParent()\");\n");
          appendDirtyJavaScript("   }\n");
          appendDirtyJavaScript("   catch(err){}\n");
          appendDirtyJavaScript("   try\n");
          appendDirtyJavaScript("   {\n");
          appendDirtyJavaScript("      window.close();\n");
          appendDirtyJavaScript("   }\n");
          appendDirtyJavaScript("   catch(err){}\n");
          appendDirtyJavaScript("}\n");  
      }
   }
}
