/*
*                 IFS Research & Development
*
*  This program is protected by copyright law and by international
*  conventions. All licensing, renting, lending or copying (including
*  for private use), and all other use of the program, which is not
*  expressively permitted by IFS Research & Development (IFS), is a
*  violation of the rights of IFS. Such violations will be reported to the
*  appropriate authorities.
*
*  VIOLATIONS OF ANY COPYRIGHT IS PUNISHABLE BY LAW AND CAN LEAD
*  TO UP TO TWO YEARS OF IMPRISONMENT AND LIABILITY TO PAY DAMAGES.
* ----------------------------------------------------------------------------
* File                          :
* Description                   :
* Notes                         :
* Other Programs Called :
* ----------------------------------------------------------------------------
* Modified    : Automatically generated by IFS/Design
* ----------------------------------------------------------------------------
*/

//-----------------------------------------------------------------------------
//-----------------------------   Package def  ------------------------------
//-----------------------------------------------------------------------------

package ifs.contrw;
//-----------------------------------------------------------------------------
//-----------------------------   Import def  ------------------------------
//-----------------------------------------------------------------------------

import java.io.UnsupportedEncodingException;
import java.text.DecimalFormat;

import ifs.docmaw.DocmawConstants;
import ifs.fnd.asp.*;
import ifs.fnd.buffer.*;
import ifs.fnd.service.*;
import ifs.fnd.*;
import ifs.genbaw.GenbawConstants;
import ifs.hzwflw.HzASPPageProviderWf;

//-----------------------------------------------------------------------------
//-----------------------------   Class def  ------------------------------
//-----------------------------------------------------------------------------

public class ProjectContract extends HzASPPageProviderWf  
{

   //-----------------------------------------------------------------------------
   //---------- Static constants ------------------------------------------------
   //-----------------------------------------------------------------------------

   public static boolean DEBUG = Util.isDebugEnabled("ifs.contrw.ProjectContract");

   //-----------------------------------------------------------------------------
   //---------- Header Instances created on page creation --------
   //-----------------------------------------------------------------------------

   private ASPBlock headblk;
   private ASPRowSet headset;
   private ASPCommandBar headbar;
   private ASPTable headtbl;
   private ASPBlockLayout headlay;

   //-----------------------------------------------------------------------------
   //---------- Item Instances created on page creation --------
   //-----------------------------------------------------------------------------

   private ASPBlock project_contract_item_blk;
   private ASPRowSet project_contract_item_set;
   private ASPCommandBar project_contract_item_bar;
   private ASPTable project_contract_item_tbl;
   private ASPBlockLayout project_contract_item_lay;

   private ASPBlock third_side_blk;
   private ASPRowSet third_side_set;
   private ASPCommandBar third_side_bar;
   private ASPTable third_side_tbl;
   private ASPBlockLayout third_side_lay;
   
   private ASPBlock second_account_blk;
   private ASPRowSet second_account_set;
   private ASPCommandBar second_account_bar;
   private ASPTable second_account_tbl;
   private ASPBlockLayout second_account_lay;
   
   private ASPBlock contract_detain_class_blk;
   private ASPRowSet contract_detain_class_set;
   private ASPCommandBar contract_detain_class_bar;
   private ASPTable contract_detain_class_tbl;
   private ASPBlockLayout contract_detain_class_lay;
   
   private ASPBlock contract_variation_blk;
   private ASPRowSet contract_variation_set;
   private ASPCommandBar contract_variation_bar;
   private ASPTable contract_variation_tbl;
   private ASPBlockLayout contract_variation_lay;

   protected DecimalFormat df;
   protected ASPTabContainer tabs;
   //-----------------------------------------------------------------------------
   //------------------------  Construction  ---------------------------
   //-----------------------------------------------------------------------------

   public  ProjectContract (ASPManager mgr, String page_path)
   {
      super(mgr, page_path);
   }
   
   protected String getDefProj() {
      ASPManager mgr = getASPManager();
      ASPContext ctx =mgr.getASPContext();
      return ctx.findGlobal(GenbawConstants.PERSON_DEFAULT_PROJECT);
   }    
  
   public void run() throws FndException
   {
      super.run();
      String comnd;  
      ASPManager mgr = getASPManager(); 
      if( mgr.commandBarActivated() ){
         comnd = mgr.readValue("__COMMAND");  
         eval(mgr.commandBarFunction());
         if (( "ITEM1.SaveReturn".equals(comnd) )|| ( "ITEM1.SaveReturn".equals(comnd) )|| ( "ITEM1.Delete".equals(comnd) )|| ( "ITEM2.SaveReturn".equals(comnd) )|| ( "ITEM1.SaveNew".equals(comnd) )|| ( "ITEM1.Delete".equals(comnd) ))
         {
            okFindITEM1();  
         }   
      }
      else if(mgr.dataTransfered())
         okFind();
      else if( !mgr.isEmpty(mgr.getQueryStringValue("SEARCH")) )
         okFind();
      else if( !mgr.isEmpty(mgr.getQueryStringValue("CONTRACT_ID")) )
         okFind();
      else if(!mgr.isEmpty(mgr.getQueryStringValue("VALIDATE")))
         validate();
      else 
         okFind();
      tabs.saveActiveTab();
      adjust();
   }
   //-----------------------------------------------------------------------------
   //------------------------  Command Bar functions  ---------------------------
   //-----------------------------------------------------------------------------

   public void  performHEAD( String command)
   {
      int currow;
      
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      

      currow = headset.getCurrentRowNo();
      if(headlay.isMultirowLayout())
         headset.storeSelections();
      else
         headset.selectRow();
      headset.markSelectedRows( command );
      mgr.submit(trans);
      headset.refreshRow();  
      headset.goTo(currow);
      headset.refreshRow();                  
   }
   public void  check()
   {

      performHEAD( "Check__" );
   }
   public void  close()
   {

      performHEAD( "Close__" );
   }

   
   public void okFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      mgr.createSearchURL(headblk);
      q = trans.addQuery(headblk);
      q.includeMeta("ALL");
      if(mgr.dataTransfered())
         q.addOrCondition(mgr.getTransferedData());
      mgr.querySubmit(trans,headblk);
      if (  headset.countRows() == 0 )
      {
         mgr.showAlert("PROJECTCONTRACTNODATA: No data found.");
         headset.clear();
      }
      eval( project_contract_item_set.syncItemSets() );
      eval( third_side_set.syncItemSets() );
      eval( second_account_set.syncItemSets() );   
      eval( contract_detain_class_set.syncItemSets() );
      eval( contract_variation_set.syncItemSets() );
   }
   
   

   public void countFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      q = trans.addQuery(headblk);
      q.setSelectList("to_char(count(*)) N");
      mgr.submit(trans);
      headlay.setCountValue(toInt(headset.getValue("N")));
      headset.clear();
   }
         
   public void newRow()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPBuffer data;
      ASPCommand cmd;
      cmd = trans.addEmptyCommand("HEAD","PROJECT_CONTRACT_API.New__",headblk);
      cmd.setOption("ACTION","PREPARE"); 
      cmd.setParameter("PROJ_NO", this.getDefProj());  
      trans = mgr.perform(trans);    
      data = trans.getBuffer("HEAD/DATA");
      headset.addRow(data);
   }


   //-----------------------------------------------------------------------------
   //------------------------  Item block cmd bar functions  ---------------------------
   //-----------------------------------------------------------------------------


   public void okFindITEM1()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;

      q = trans.addQuery(project_contract_item_blk);
      q.addWhereCondition("PROJ_NO = ? AND CONTRACT_ID = ?");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      q.addOrderByClause("FULL_PATH,ITEM_NO");       
      q.includeMeta("ALL");
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,project_contract_item_blk);
      headset.goTo(headrowno);
   }
   
   public void newRowITEM1()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      ASPBuffer data;

      
      cmd = trans.addEmptyCommand("ITEM1","PROJECT_CONTRACT_ITEM_API.New__",project_contract_item_blk);
      cmd.setOption("ACTION","PREPARE");
      cmd.setParameter("ITEM0_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ITEM0_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      cmd.setParameter("ITEM_CURRENCY","CNY");
      cmd.setParameter("ITEM_EXCHANGE_RATE", "1");  
      cmd.setParameter("ITEM_TYPE", "ITEM");  
        
      trans = mgr.perform(trans);
      data = trans.getBuffer("ITEM1/DATA");    
      project_contract_item_set.addRow(data);
   }
   
   public void okFindITEM2()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;

      q = trans.addQuery(third_side_blk);
      q.addWhereCondition("PROJ_NO = ? AND CONTRACT_ID = ?");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      q.includeMeta("ALL");    
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,third_side_blk);
      headset.goTo(headrowno);
   }
   public void newRowITEM2()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      ASPBuffer data;

      
      cmd = trans.addEmptyCommand("ITEM2","THIRD_SIDE_API.New__",third_side_blk);
      cmd.setOption("ACTION","PREPARE");
      cmd.setParameter("ITEM1_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ITEM1_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      trans = mgr.perform(trans);
      data = trans.getBuffer("ITEM2/DATA");
      third_side_set.addRow(data);
   }

   public void okFindITEM4()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;

      q = trans.addQuery(second_account_blk);
      q.addWhereCondition("PROJ_NO = ? AND CONTRACT_ID = ?");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      q.includeMeta("ALL");
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,second_account_blk);
      headset.goTo(headrowno);
   }
   
   public void newRowITEM4()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      ASPBuffer data;

      
      cmd = trans.addEmptyCommand("ITEM4","SECOND_ACCOUNT_API.New__",second_account_blk);
      cmd.setOption("ACTION","PREPARE");
      cmd.setParameter("ITEM3_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ITEM3_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      trans = mgr.perform(trans);
      data = trans.getBuffer("ITEM4/DATA");
      second_account_set.addRow(data);
   }
   
   public void okFindDetainClass()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;
      q = trans.addQuery(contract_detain_class_blk);  
      q.addWhereCondition("PROJ_NO = ? AND CONTRACT_ID = ?");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      q.includeMeta("ALL");
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,contract_detain_class_blk);
      headset.goTo(headrowno);      
   }

   public void newRowDetainClass()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPBuffer data;
      ASPCommand cmd;
   
      cmd = trans.addEmptyCommand("DETAINCLASS","PROJECT_CONTRACT_DETAIN_API.New__",contract_detain_class_blk);
      cmd.setOption("ACTION","PREPARE");    
      cmd.setParameter("DETAINCLASS_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("DETAINCLASS_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      trans = mgr.perform(trans);    
      data = trans.getBuffer("DETAINCLASS/DATA");
      contract_detain_class_set.addRow(data);
   } 
   
   public void okFindITEM5()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;

      q = trans.addQuery(contract_variation_blk);
      q.addWhereCondition("PROJ_NO = ? AND CONTRACT_ID = ? AND OBJSTATE = 'Released' ");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      q.includeMeta("ALL");
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,contract_variation_blk);
      headset.goTo(headrowno);
   }
   
   public void newRowITEM5()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      ASPBuffer data;

      
      cmd = trans.addEmptyCommand("ITEM1","CONTRACT_VARIATION_API.New__",contract_variation_blk);
      cmd.setOption("ACTION","PREPARE");
      cmd.setParameter("ITEM5_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ITEM5_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      trans = mgr.perform(trans);
      data = trans.getBuffer("ITEM5/DATA");    
      contract_variation_set.addRow(data);
   }
   //-----------------------------------------------------------------------------
   //------------------------  Predefines Head ---------------------------
   //-----------------------------------------------------------------------------

   public void preDefine()
   {
      ASPManager mgr = getASPManager();

      headblk = mgr.newASPBlock("MAIN");
      headblk.addField("OBJID").
              setHidden();
      headblk.addField("OBJVERSION").
              setHidden();
      headblk.addField("OBJSTATE").
              setHidden();
      headblk.addField("OBJEVENTS").
              setHidden(); 
      headblk.addField("PROJ_NO").
              setMandatory().
              setWfProperties(). 
              setInsertable().
              setDynamicLOV("GENERAL_PROJECT").
              setLabel("PROJECTCONTRACTPROJNO: Proj No").
              setSize(20);  
      headblk.addField("GENERAL_PROJECT_PROJ_DESC").
              setReadOnly().
              setWfProperties(). 
              setFunction("GENERAL_PROJECT_API.GET_PROJ_DESC (:PROJ_NO)").
              setLabel("PROJECTCONTRACTGENERALPROJECTPROJDESC: General Project Proj Desc").
              setSize(20);
      mgr.getASPField("PROJ_NO").setValidation("GENERAL_PROJECT_PROJ_DESC");
      headblk.addField("CONTRACT_ID"). 
              setWfProperties(). 
              setUpperCase().  
              setInsertable().  
              setLabel("PROJECTCONTRACTCONTRACTID: Contract Id").
              setSize(20);   
     headblk.addField("CONTRACT_DESC").
             setMandatory().
             setWfProperties(). 
             setInsertable().
             setLabel("PROJECTCONTRACTCONTRACTDESC: Contract Desc").
             setSize(120);    
   //add by lhh 20150426
     headblk.addField("CONTRACT_SHORT_DESC").
             setInsertable().
             setDefaultNotVisible().
             setLabel("PROJECTCONTRACTCONTRACTSHORTDESC: Contract Short Desc").
             setSize(20);    
     
//add by lhh 20141205
      headblk.addField("VIEW_REF_FILE").
           setReadOnly().
            unsetQueryable().
            setFunction("''").
           setLabel("PROJECTCONTRACTVIEWREFFILE: View File").
           setHyperlink( mgr.getApplicationPath()
              + "/" + mgr.getConfigParameter("DOCMAW/DOC_REF_URL")
              + "?VIEW=" + mgr.URLEncode("PROJECT_CONTRACT"), "OBJID", "NEWWIN").
           setAsImageField();
       headblk.addField("LU_NAME").
             setHidden();
       headblk.addField("KEY_REF").
             setHidden();
       headblk.addField("EXIST_DOC_REF").
             setHidden().
             setCheckBox("FALSE,TRUE").
             setFunction("Doc_Reference_Object_API.Exist_Obj_Reference(:LU_NAME, :KEY_REF)").
             setSize(5);
//add by lhh 20141205  end  

      headblk.addField("CONTRACT_TYPE").
              enumerateValues("Contract_Type_API").
              setSelectBox().
              setDefaultNotVisible().
              setInsertable().
              setHidden(). 
              setLabel("PROJECTCONTRACTCONTRACTTYPE: Contract Type").
              setSize(20);
      headblk.addField("BACK_FILE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTBACKFILE: Back File").
              setSize(5).
              setCheckBox("F,T");
      headblk.addField("FIRST_SIDE").
              setInsertable().
              setDefaultNotVisible().
              setDynamicLOV("GENERAL_ZONE").
              setLabel("PROJECTCONTRACTFIRSTSIDE: First Side").
              setSize(20); 
      headblk.addField("FIRST_SIDE_NAME").
              setSize(20).
              setMaxLength(140).         
              setReadOnly().
              setFunction("GENERAL_ZONE_API.Get_Zone_Desc(:FIRST_SIDE)").
              setLabel("PROJECTCONTRACTFIRSTSIDENAME: First Side Name");
      mgr.getASPField("FIRST_SIDE").setValidation("FIRST_SIDE_NAME");
      headblk.addField("SECEND_SIDE").
              setInsertable().
              setDefaultNotVisible().
              setMandatory().
              setDynamicLOV("SUPPLIER_INFO").
              setLabel("PROJECTCONTRACTSECENDSIDE: Secend Side").
              setSize(20);
      headblk.addField("SECEND_SIDE_NAME").
              setSize(20).
              setMaxLength(140).
              setReadOnly().
              setFunction("SUPPLIER_INFO_API.GET_NAME(:SECEND_SIDE)").    
              setLabel("PROJECTCONTRACTSECENDSIDENAME: Secend Side Name");
      mgr.getASPField("SECEND_SIDE").setValidation("SECEND_SIDE_NAME");
      headblk.addField("FIRST_PERSON").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTFIRSTPERSON: First Person").
              setDynamicLOV("PERSON_INFO").
              setSize(20);
      headblk.addField("FIRST_PERSON_NAME").
              setReadOnly().
              setLabel("PROJECTCONTRACTFIRSTPERSONNAME: First Person Name").
              setFunction("PERSON_INFO_API.Get_Name(:FIRST_PERSON)").
              setSize(20);  
      mgr.getASPField("FIRST_PERSON").setValidation("FIRST_PERSON_NAME");
      headblk.addField("BID_ID").
              setInsertable().
              setHidden(). 
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTBIDID: Bid Id").
              setSize(20); 
      headblk.addField("HAS_DOC").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTHASDOC: Has Doc").
              setSize(5).setCheckBox("F,T");
      headblk.addField("LOCKED").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTLOCKED: Locked").
              setSize(5).setCheckBox("F,T");
      headblk.addField("OPENING_CONTRACT").
              setDefaultNotVisible().
              setInsertable().     
              setLabel("PROJECTCONTRACTOPENINGCONTRACT: Opening Contract").
              setSize(5).setCheckBox("F,T");
      headblk.addField("GUARANTEE_CONTRACT").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTGUARANTEECONTRACT: Guarantee Contract").
              setSize(5).setCheckBox("F,T");
      headblk.addField("GUARANTEE_TERM","Date").
              setHidden().
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTGUARANTEETERM: Guarantee Term").
              setSize(20);
      headblk.addField("GET_BID_PRICE","Number","#0.00").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTGETBIDPRICE: Get Bid Price").
              setSize(20);
      headblk.addField("SIGN_PRICE","Number","#0.00").
              setFunction("PROJECT_CONTRACT_API.Cal_Ori_Contract_Total(:PROJ_NO, :CONTRACT_ID)").
              setInsertable().
              setLabel("PROJECTCONTRACTSIGNPRICE: Sign Price").
              setSize(20);  
      headblk.addField("CHANGE_DIFF_PRICE","Number","#0.00").
              unsetInsertable().
              setReadOnly().
              setFunction("PROJECT_CONTRACT_API.Cal_Chg_Contract_Diff_Total(:PROJ_NO, :CONTRACT_ID)").
              setLabel("PROJECTCONTRACTCHANGEDIFFPRICE: Change Diff Price").
              setSize(20);      
      headblk.addField("CHANGE_PRICE","Number","#0.00").
              unsetInsertable().
              setReadOnly().
              setFunction("PROJECT_CONTRACT_API.Cal_Chg_Contract_Total(:PROJ_NO, :CONTRACT_ID)").
              setLabel("PROJECTCONTRACTCHANGEPRICE: Change Price").  
              setSize(20);      
      headblk.addField("SAVE_GUARANTEE_PEICE","Number" ,"#0.00").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSAVEGUARANTEEPEICE: Save Guarantee Peice").
              setSize(20);
      headblk.addField("QUALITY_GUARANTEE_PRICE","Number" ,"#0.00").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTQUALITYGUARANTEEPRICE: Quality Guarantee Price").
              setSize(20);
      headblk.addField("WORKER_PAY_GUARANTEE_PRICE","Number" ,"#0.00").
              setInsertable().
              setLabel("PROJECTCONTRACTWORKERPAYGUARANTEEPRICE: Worker Pay Guarantee Price").
              setSize(20);  
      headblk.addField("PERPAY_PRICE","Number" ,"#0.00").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTPERPAYPRICE: Perpay Price").
              setSize(20);
      headblk.addField("MAIN_CONTRACT").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTMAINCONTRACT: Main Contract").
              setSize(140).  
              setHeight(4);
      headblk.addField("DESIGNATION_DATE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTDESIGNATIONDATE: Designation Date").
              setSize(140).
              setHeight(4);
      headblk.addField("PAY_PROMISE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTPAYPROMISE: Pay Promise").
              setSize(140).
              setHeight(4);
      headblk.addField("SUPPLY_RANGE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSUPPLYRANGE: Supply Range").
              setSize(140).
              setHeight(4);
      headblk.addField("ACCEPT_CONDITION").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTACCEPTCONDITION: Accept Condition").
              setSize(140).
              setHeight(4);
      headblk.addField("DELIVERY_DATE").  
              setInsertable().
              setLabel("PROJECTCONTRACTDELIVERYDATE: Delivery Date").
              setSize(140).
              setDefaultNotVisible().
              setHeight(4);
      headblk.addField("RECEIPT").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTRECEIPT: Receipt").
              setSize(140).
              setHeight(4);
      headblk.addField("SING_DATE","Date").
              setInsertable().
              setMandatory().
              setLabel("PROJECTCONTRACTSINGDATE: Sing Date").
              setSize(20);
      headblk.addField("EFFECT_DATE","Date").
              setInsertable().
              setLabel("PROJECTCONTRACTEFFECTDATE: Effect Date").
              setSize(20);
      headblk.addField("START_WORK_DATE","Date").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSTARTWORKDATE: Start Work Date").
              setSize(20);
      headblk.addField("COMPLETE_DATE","Date").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTCOMPLETEDATE: Complete Date").
              setSize(20);
      headblk.addField("CONTRACT_TIME_LIMIT","Number").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTCONTRACTTIMELIMIT: Contract Time Limit").
              setSize(20);
      headblk.addField("REAL_TIME_LIMIT","Number").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTREALTIMELIMIT: Real Time Limit").
              setSize(20);
      headblk.addField("EFFICIENCY_TERM","Date").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTEFFICIENCYTERM: Efficiency Term").
              setSize(20);
      headblk.addField("DATE_NOTE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTDATENOTE: Date Note").
              setSize(140).
              setHeight(4);
      headblk.addField("TRANSPORT_METH").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTTRANSPORTMETH: Transport Meth").
              setSize(140).
              setHeight(4);
      headblk.addField("GUAR_PRICE_EXE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTGUARPRICEEXE: Guar Price Exe").
              setSize(5).
              setCheckBox("F,T");
      headblk.addField("THIRD_SIDE").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTTHIRDSIDE: Third Side").
              setSize(100);
      headblk.addField("THIRD_REMARK").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTTHIRDREMARK: Third Remark").
              setSize(2000);
      headblk.addField("SHANGWU_PERSON").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSHANGWUPERSON: Shangwu Person").
              setSize(100);
      headblk.addField("ZHIBAO_PERSON").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTZHIBAOPERSON: Zhibao Person").
              setSize(100);
      headblk.addField("THIRD_SIDE_NAME").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTTHIRDSIDENAME: Third Side Name").
              setSize(100);
      headblk.addField("JISHU_PERSON").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTJISHUPERSON: Jishu Person").
              setSize(100);
      headblk.addField("CHENGTAO_INTER_ID").
              setInsertable().
              setHidden().
              setLabel("PROJECTCONTRACTCHENGTAOINTERID: Chengtao Inter Id").
              setSize(100);
      headblk.addField("GONGCHENG_INTER_ID").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTGONGCHENGINTERID: Gongcheng Inter Id").
              setSize(100);
      headblk.addField("FIRST_BANK").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTFIRSTBANK: First Bank").
              setSize(20);
      headblk.addField("FIRST_ACCOUNTS").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTFIRSTACCOUNTS: First Accounts").
              setSize(20);
      headblk.addField("FIRST_TEL").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTFIRSTTEL: First Tel").
              setSize(20);
      headblk.addField("FIRST_MAIL").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTFIRSTMAIL: First Mail").
              setSize(20);
      headblk.addField("SECOND_REMARK").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECONDREMARK: Second Remark").
              setSize(140).
              setHeight(4);
      headblk.addField("JFFZR").
              setInsertable().  
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTJFFZR: Jffzr").
              setSize(100);
      headblk.addField("JFFZR_NAME").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTJFFZRNAME: Jffzr Name").
              setSize(100);
      headblk.addField("SECOND_PERSON").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECONDPERSON: Second Person").
              setSize(20);
      headblk.addField("SECOND_PERSON_NAME").
              setReadOnly().
              setLabel("PROJECTCONTRACTSECONDPERSONNAME: Second Person Name").
              setFunction("PERSON_INFO_API.Get_Name(:SECOND_PERSON)").
              setSize(20);      
      headblk.addField("SECOND_BANK").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTSECONDBANK: Second Bank").
              setSize(20);
      headblk.addField("SECOND_ACCOUNTS").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTSECONDACCOUNTS: Second Accounts").
              setSize(100);
      headblk.addField("SECOND_TEL").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECONDTEL: Second Tel").
              setSize(20);
      headblk.addField("SECOND_MAIL").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECONDMAIL: Second Mail").
              setSize(20);
      headblk.addField("SECOND_FACSIMILE").
              setInsertable().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECONDFACSIMILE: Second Facsimile").
              setSize(20);
      headblk.addField("THIRD").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTTHIRD: Third").
              setSize(100);
      headblk.addField("THIRD_PERSON").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTTHIRDPERSON: Third Person").
              setSize(100);
      headblk.addField("SECRECY_LEVEL").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTSECRECYLEVEL: Secrecy Level").
              setSize(10);
      headblk.addField("AUTHORIZE").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZE: Authorize").
              setSize(100);
      headblk.addField("AUTHORIZE_PERSON").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEPERSON: Authorize Person").
              setSize(100);
      headblk.addField("AUTHORIZE_PERSON_NAME").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEPERSONNAME: Authorize Person Name").
              setSize(100);
      headblk.addField("AUTHORIZE_PERSON2").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEPERSON2: Authorize Person2").
              setSize(100);
      headblk.addField("AUTHORIZE_PERSON2_NAME").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEPERSON2NAME: Authorize Person2 Name").
              setSize(100);
      headblk.addField("AUTHORIZE_MONEY","Number").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEMONEY: Authorize Money").
              setSize(20);
      headblk.addField("AUTHORIZE_DATE","Date").
              setInsertable().
              setDefaultNotVisible().
              setHidden().
              setLabel("PROJECTCONTRACTAUTHORIZEDATE: Authorize Date").
              setSize(20);
      headblk.addField("AUTHORIZE_REMARK").
              setInsertable().
              setHidden().
              setDefaultNotVisible().
              setLabel("PROJECTCONTRACTAUTHORIZEREMARK: Authorize Remark").
              setSize(2000);
      headblk.addField("SCHEDULE").
              setInsertable().
              setDefaultNotVisible().
              setMandatory().
              setCheckBox("FALSE,TRUE").  
              setLabel("PROJECTCONTRACTSCHEDULE: Schedule").
              setSize(5);
      headblk.addField("EXCHANGE_RATE","Number").
              setInsertable().
              setDefaultNotVisible().
              setHidden().     
              setLabel("PROJECTCONTRACTEXCHANGERATE: Exchange Rate").
              setSize(20);
      headblk.addField("CAL_MARK").
              setDefaultNotVisible().
              setInsertable().
              setLabel("PROJECTCONTRACTCALMARK: Cal Mark").
              setHidden().
              setSize(5);
      headblk.addField("STATUS").
              setReadOnly(). 
              setLabel("PROJECTCONTRACTSTATUS: Status").
              setSize(20);  
      headblk.addField("PRE_CONTRACT_NO").
              setInsertable().
              setLabel("PROJECTCONTRACTPRECONTRACTNO: Pre Contract No").
              setSize(20);
      headblk.addField("CLASS_NO").
              setInsertable().
              setDefaultNotVisible().
              setUpperCase().
              setMandatory().
              setDynamicLOV("CONTRACT_CLASS").
              setLabel("PROJECTCONTRACTCONTRACTCLASS: Contract Class").
              setSize(20);
      headblk.addField("CONTRACT_CLASS_NAME").
              setReadOnly().  
              setFunction("Contract_Class_API.Get_Class_Name(:CLASS_NO)").
              setLabel("PROJECTCONTRACTCONTRACTCLASSNAME: Class Name").
              setSize(20);
      mgr.getASPField("CLASS_NO").setValidation("CONTRACT_CLASS_NAME");
      headblk.addField("PURCH_TYPE_NO").
              setInsertable().
              setDefaultNotVisible().
              setDynamicLOV("CONTRACT_PURCH_TYPE").
              setLabel("PROJECTCONTRACTPURCHTYPE: Purch Type").
              setSize(20);
      headblk.addField("PURCH_TYPE_DESC").    
               setReadOnly().
               setFunction("CONTRACT_PURCH_TYPE_API.Get_Description(:PURCH_TYPE_NO)").
               setLabel("PROJECTCONTRACTPURCHTYPEDESC: Purch Type Desc").
               setSize(20);
      headblk.addField("STATE").
               setLabel("PROJECTCONTRACTSTATE: State").
               setReadOnly().
               setSize(30);  
      headblk.addField("ALL_PAY_CST", "Money" ,"#0.00").
              setReadOnly(). 
              setFunction("Contract_Payment_API.Cal_All_Contract_Payment(:PROJ_NO,:CONTRACT_ID,1000000000)").    
              setLabel("CONTRACTPAYMENTALLPAYCST: All Pay Cst").
              setSize(20);     
      mgr.getASPField("PURCH_TYPE_NO").setValidation("PURCH_TYPE_DESC");
      headblk.addField("SETTLEMENT_PRICE", "Money" ,"#0.00").
              setInsertable().
              setLabel("PROJECTCONTRACTSETTLEMENTPRICE: Settlement Price").
              setSize(20);
      

      headblk.setView("PROJECT_CONTRACT");
      headblk.defineCommand("PROJECT_CONTRACT_API","New__,Modify__,Remove__,Check__,Close__");
      headset = headblk.getASPRowSet();  
      headbar = mgr.newASPCommandBar(headblk);  
      headbar.enableMultirowAction();         
      headbar.addSecureCustomCommand("Check","PROJECTCONTRACTCHECK: Check Project Contract", "PROJECT_CONTRACT_API.Check__");
      headbar.addSecureCustomCommand("Close","PROJECTCONTRACTCLOSE: Close Project Contract", "PROJECT_CONTRACT_API.Close__");
      headbar.addCommandValidConditions("Check",     "OBJSTATE",    "Enable",      "Planed");
      headbar.addCommandValidConditions("Close", "OBJSTATE",    "Enable",      "Checked");  
      headbar.addCustomCommand("printReport", "PROJECTCONTRACTPRINTREPORT: Print Report...");
      headtbl = mgr.newASPTable(headblk);          
      headtbl.setTitle("PROJECTCONTRACTTBLHEAD: Project Contracts");
      headtbl.enableRowSelect();
      headtbl.setWrap();
      headlay = headblk.getASPBlockLayout();
      headlay.setDefaultLayoutMode(headlay.MULTIROW_LAYOUT);
      headlay = headblk.getASPBlockLayout();
      headlay.setDefaultLayoutMode(headlay.MULTIROW_LAYOUT);
      headlay.setDialogColumns(3);  
      headlay.setDataSpan("DATE_NOTE",12 );
      headlay.setDataSpan("CONTRACT_DESC"    , 12 );  
      headlay.setDataSpan("CONTRACT_SHORT_DESC"    , 12 );  
      headlay.setDataSpan("SECOND_REMARK"    , 12 );
      headlay.setDataSpan("MAIN_CONTRACT"    , 12 );
      headlay.setDataSpan("DESIGNATION_DATE" , 12 );
      headlay.setDataSpan("PAY_PROMISE"      , 12 );  
      headlay.setDataSpan("SUPPLY_RANGE"     , 12 );
      headlay.setDataSpan("ACCEPT_CONDITION" , 12 );
      headlay.setDataSpan("DELIVERY_DATE"    , 12 );
      headlay.setDataSpan("RECEIPT"          , 12);
      headlay.setDataSpan("SECOND_FACSIMILE" , 12 );  
      headlay.setDataSpan("GONGCHENG_INTER_ID",12);      
      headlay.setSimple  ("FIRST_SIDE_NAME"       );  
      headlay.setSimple  ("FIRST_PERSON_NAME"     );
      headlay.setSimple  ("SECEND_SIDE_NAME"      );
      headlay.setSimple  ("SECOND_PERSON_NAME"    );
      headlay.setSimple  ("PURCH_TYPE_DESC");  
      headlay.setSimple  ("CONTRACT_CLASS_NAME");
      headlay.setSimple  ("GENERAL_PROJECT_PROJ_DESC");
         
      headlay.defineGroup(mgr.translate("DEFINEGROUPCONTRACTBASEINFO: Contract base info"),
            "PROJ_NO,"                      +
            "GENERAL_PROJECT_PROJ_DESC,"    +
            "CONTRACT_ID,"                  +
            "PRE_CONTRACT_NO,"              +  
            "VIEW_REF_FILE,"              +      
            "CONTRACT_DESC,"                +
            "CONTRACT_TYPE,"                +  
            "CLASS_NO,"                     +
            "CONTRACT_CLASS_NAME,"          +
            "PURCH_TYPE_NO,"                +
            "PURCH_TYPE_DESC,"              +
            "BID_ID,"                       +
               "GUARANTEE_TERM,"            +
               "SING_DATE,"                 +
               "EFFECT_DATE,"               +
               "START_WORK_DATE,"           +
               "COMPLETE_DATE,"             +
               "CONTRACT_TIME_LIMIT,"       +
               "REAL_TIME_LIMIT,"           +
               "EFFICIENCY_TERM,"           +
               "SCHEDULE,"                  +
               "HAS_DOC,"                +
               "STATE,"    +         
               "CONTRACT_SHORT_DESC,"    +         
               "DATE_NOTE" ,
               false, true);    
         headlay.defineGroup("合同参与者", 
            "FIRST_SIDE,"                +
            "FIRST_SIDE_NAME,"           +
            "FIRST_PERSON,"              +
            "FIRST_PERSON_NAME,"         +
               "SECEND_SIDE,"            +
               "SECEND_SIDE_NAME,"       +
               "SECOND_PERSON,"          +
               "SECOND_PERSON_NAME,"     +
               "SECOND_TEL,"             +
               "SECOND_MAIL,"            +
               "SECOND_FACSIMILE,"       +
               "SECOND_REMARK"   ,       
               true, false);
         headlay.defineGroup("金额", 
            "EXCHANGE_RATE,"          +
            "GET_BID_PRICE,"          +
            "SIGN_PRICE,"             +
            "CHANGE_DIFF_PRICE,"      +
            "CHANGE_PRICE,"           +  
            "CHANGE_PRICE,"           +
            "WORKER_PAY_GUARANTEE_PRICE,"+
            "ALL_PAY_CST,"               +
            "SETTLEMENT_PRICE",                      
             true, false);  
            
         headlay.defineGroup("说明",   
            "MAIN_CONTRACT,"              +
            "DESIGNATION_DATE,"           +
            "PAY_PROMISE,"                +
            "SUPPLY_RANGE,"               +
            "ACCEPT_CONDITION,"           +
            "DELIVERY_DATE,"              +
            "RECEIPT,"                 +
            "TRANSPORT_METH", 
            true, false);  

         project_contract_item_blk = mgr.newASPBlock("ITEM1");
         project_contract_item_blk.addField("ITEM0_OBJID").
                                   setHidden().
                                   setDbName("OBJID");
         project_contract_item_blk.addField("ITEM0_OBJVERSION").
                                   setHidden().
                                   setDbName("OBJVERSION");
         project_contract_item_blk.addField("ITEM0_CONTRACT_ID").
                                   setDbName("CONTRACT_ID").
                                   setMandatory().
                                   setInsertable().
                                   setHidden().
                                   setLabel("PROJECTCONTRACTITEMITEM0CONTRACTID: Contract Id").
                                   setSize(20);
         project_contract_item_blk.addField("ITEM0_PROJ_NO").
                                   setDbName("PROJ_NO").
                                   setMandatory().
                                   setInsertable().
                                   setHidden().
                                   setLabel("PROJECTCONTRACTITEMITEM0PROJNO: Proj No").
                                   setSize(20);
         // 2
         
         project_contract_item_blk.addField("ITEM_NO").
                                   setMandatory().
                                   setInsertable().
                                   setReadOnly().
                                   setLabel("PROJECTCONTRACTITEMITEMNO: Item No").
                                   setSize(20);
         
         project_contract_item_blk.addField("PRE_ITEM_NO").
                                   setInsertable().
                                   setReadOnly().
                                   setLabel("PROJECTCONTRACTITEMPREITEMNO: Pre Item No").
                                   setSize(20);
         
         project_contract_item_blk.addField("ITEM_DESC").
                                   setInsertable().
                                   setMandatory().
                                   setLabel("PROJECTCONTRACTITEMITEMDESC: Item Desc").
                                   setSize(30);
         
         // 3
         project_contract_item_blk.addField("ITEM_TYPE").
                                   setInsertable().    
                                   setCheckBox("FOLDER,ITEM").
                                   setCustomValidation("ITEM_TYPE", "ITEM_UNIT,ITEM_CURRENCY,ITEM_EXCHANGE_RATE,PRICE,ORIGINAL_QTY,ORIGINAL_TOTAL").
                                   setLabel("PROJECTCONTRACTITEMITEMTYPE: Item Type").
                                   setSize(10);
         project_contract_item_blk.addField("ITEM_UNIT").
                                   setInsertable().
                                   setDynamicLOV("ISO_UNIT").
                                   setLabel("PROJECTCONTRACTITEMITEMUNIT: Item Unit").
                                   setSize(10);
         project_contract_item_blk.addField("ITEM_UNIT_DESC").
                                   setReadOnly().
                                   setLabel("PROJECTCONTRACTITEMITEMUNITDESC: Item Unit Desc").
                                   setFunction("Iso_Unit_API.Get_Description(:ITEM_UNIT)").
                                   setSize(10);
         mgr.getASPField("ITEM_UNIT").setValidation("ITEM_UNIT_DESC");
         
         // 4
         project_contract_item_blk.addField("ITEM_CURRENCY").
                                   setInsertable().
                                   setLabel("PROJECTCONTRACTITEMITEMCURRENCY: Item Currency").
                                   setDynamicLOV("ISO_CURRENCY").
                                   setSize(10);
         project_contract_item_blk.addField("ITEM_CURRENCY_DESC").
                                   setReadOnly().
                                   setLabel("PROJECTCONTRACTITEMITEMCURRENCYDESC: Item Currency Desc").
                                   setFunction("Iso_Currency_API.Get_Description(:ITEM_CURRENCY)").
                                   setSize(10);
         mgr.getASPField("ITEM_CURRENCY").setValidation("ITEM_CURRENCY_DESC");
         project_contract_item_blk.addField("CONTRACT_ITEM_REP_TYPE").
                                    enumerateValues("Contract_Item_Rep_Type_API").
                                    setSelectBox().  
                                    setHidden().
                                    setInsertable().    
                                    setLabel("PROJECTCONTRACTITEMITEMREPTYPE: Item Rep Type").
                                    setSize(20);  
         project_contract_item_blk.addField("ITEM_EXCHANGE_RATE", "Number").
                                   setDbName("EXCHANGE_RATE").
                                   setInsertable().  
                                   setLabel("PROJECTCONTRACTITEMEXCHANGERATE: Exchange Rate").
                                   setSize(10);
         
         // 5
         project_contract_item_blk.addField("NEW_ITEM").
                                   setReadOnly().
                                   setHidden().
                                   setCheckBox("FALSE,TRUE").
                                   setLabel("PROJECTCONTRACTITEMNEWITEM: New Item").
                                   setSize(5);
         project_contract_item_blk.addField("PRICE", "Money").  
                                   setInsertable().
                                   setLabel("PROJECTCONTRACTITEMPRICE: Price").
                                   setCustomValidation("PRICE,ORIGINAL_QTY","ORIGINAL_TOTAL").
                                   setSize(20);
         // 6
         project_contract_item_blk.addField("ORIGINAL_QTY", "Number","#0.00").
                                   setInsertable().   
                                   setLabel("PROJECTCONTRACTITEMORIGINALQTY: Original Qty").
                                   setCustomValidation("PRICE,ORIGINAL_QTY","ORIGINAL_TOTAL").
                                   setSize(20);
         
         project_contract_item_blk.addField("ORIGINAL_TOTAL", "Money" ,"#0.00").
                                   setInsertable().  
                                   setLabel("PROJECTCONTRACTITEMORIGINALTOTAL: Original Total").
                                   setSize(20);
         
         
         project_contract_item_blk.addField("CHANGED_DIFF_QTY", "Number" ,"#0.00").
                                   setReadOnly().
                                   setFunction("PROJECT_CONTRACT_ITEM_API.Cal_Changed_Diff_Qty(:PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
                                   setLabel("PROJECTCONTRACTITEMCHANGEDDIFFQTY: Changed Diff Qty").
                                   setSize(20);
         project_contract_item_blk.addField("CHANGED_DIFF_TOTAL", "Number" ,"#0.00").
                                   setReadOnly().
                                   setFunction("PROJECT_CONTRACT_ITEM_API.Cal_Changed_Diff_Total(:PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
                                   setLabel("PROJECTCONTRACTITEMCHANGEDDIFFTOTAL: Changed Diff Total").
                                   setSize(20);
         // 7  
         project_contract_item_blk.addField("CHANGED_QTY", "Number" ,"#0.00").
                                   setReadOnly().
                                   setLabel("PROJECTCONTRACTITEMCHANGEDQTY: Changed Qty").
                                   setSize(20);
         project_contract_item_blk.addField("CHANGED_TOTAL", "Money" ,"#0.00").
                                   setReadOnly().   
                                   setLabel("PROJECTCONTRACTITEMCHANGEDTOTAL: Changed Total").
                                   setSize(20);
         //8
         project_contract_item_blk.addField("BUDGET_NO").
                                    setInsertable().
                                    setHidden().
                                    setLabel("PROJECTCONTRACTITEMBUDGETNO: Budget No").
                                    setSize(50);
         project_contract_item_blk.addField("BUDGET_LINE_NO").
                                   setDynamicLOV("PROJECT_BUDGET_LINE","PROJ_NO").
                                   setLOVProperty("WHERE", "STATUS='1'").  
                                   setLOVProperty("ORDER_BY", "SEQ_NO").
                                   setLOVProperty("TREE_PARE_FIELD", "PARENT_NO").
                                   setLOVProperty("TREE_DISP_FIELD", "BUDGET_LINE_NO,BUDGET_NAME").
                                   setInsertable().        
                                   setLabel("PROJECTCONTRACTITEMBUDGETLINENO: Budget Line No").
                                   setSize(50);
         project_contract_item_blk.addField("BUDGET_LINE_NAME").
                                   setReadOnly().        
                                   setFunction("PROJECT_BUDGET_LINE_API.Get_Budget_Name(:PROJ_NO,:BUDGET_LINE_NO)").
                                   setLabel("PROJECTCONTRACTITEMBUDGETLINENAME: Budget Line Name").
                                   setSize(50);
         mgr.getASPField("BUDGET_LINE_NO").setValidation("BUDGET_LINE_NAME");
         // 9    
         project_contract_item_blk.addField("ITEM_NOTE").
                                   setInsertable().
                                   setLabel("PROJECTCONTRACTITEMITEMNOTE: Item Note").
                                   setSize(140).setHeight(3);
        
         // Hidden fields
         project_contract_item_blk.addField("FULL_PATH").
                                   setHidden().
                                   setLabel("PROJECTCONTRACTITEMFULLPATH: Full Path").
                                   setSize(50); 
         
      project_contract_item_blk.setView("PROJECT_CONTRACT_ITEM");
      project_contract_item_blk.defineCommand("PROJECT_CONTRACT_ITEM_API","New__,Modify__,Remove__");
      project_contract_item_blk.setMasterBlock(headblk);
      project_contract_item_set = project_contract_item_blk.getASPRowSet();
      project_contract_item_bar = mgr.newASPCommandBar(project_contract_item_blk);
      project_contract_item_bar.defineCommand(project_contract_item_bar.OKFIND, "okFindITEM1");
      project_contract_item_bar.defineCommand(project_contract_item_bar.NEWROW, "newRowITEM1");
      project_contract_item_tbl = mgr.newASPTable(project_contract_item_blk);
      project_contract_item_tbl.setTitle("PROJECTCONTRACTITEMITEMHEAD1: ProjectContractItem");
      project_contract_item_tbl.enableRowSelect();
      project_contract_item_tbl.setWrap();
      project_contract_item_lay = project_contract_item_blk.getASPBlockLayout();
      project_contract_item_lay.setDefaultLayoutMode(project_contract_item_lay.MULTIROW_LAYOUT);
      project_contract_item_lay.setSimple("ITEM_UNIT_DESC");
      project_contract_item_lay.setSimple("ITEM_CURRENCY_DESC");
      project_contract_item_lay.setSimple("BUDGET_LINE_NAME"); 
      project_contract_item_lay.setDataSpan("ITEM_NOTE", 5);
      project_contract_item_lay.setDataSpan("BUDGET_LINE_NO", 5);   
        
      
      third_side_blk = mgr.newASPBlock("ITEM2");  
      third_side_blk.addField("ITEM1_OBJID").
                     setHidden().
                     setDbName("OBJID");
      third_side_blk.addField("ITEM1_OBJVERSION").
                     setHidden().
                     setDbName("OBJVERSION");
      third_side_blk.addField("ITEM1_PROJ_NO").
                     setDbName("PROJ_NO").
                     setHidden().
                     setMandatory().
                     setInsertable().
                     setLabel("THIRDSIDEITEM1PROJNO: Proj No").
                     setSize(50);
      third_side_blk.addField("ITEM1_CONTRACT_ID").
                     setDbName("CONTRACT_ID").
                     setMandatory().
                     setHidden().
                     setInsertable().
                     setLabel("THIRDSIDEITEM1CONTRACTID: Contract Id").
                     setSize(100);
      third_side_blk.addField("SECOND_ID").
                     setMandatory().
                     setDynamicLOV("SUPPLIER_INFO").
                     setInsertable().  
                     setLabel("THIRDSIDESECONDID: Third Id").
                     setSize(30);
      third_side_blk.addField("SECOND_NAME").
                     setReadOnly().
                     setFunction("SUPPLIER_INFO_API.GET_NAME(:SECOND_ID)").
                     setLabel("THIRDSIDESECONDNAME: Third Name").  
                     setSize(30);  
      mgr.getASPField("SECOND_ID").setValidation("SECOND_NAME");
      third_side_blk.addField("IS_USE").
                     setInsertable().
                     setHidden().
                     setLabel("THIRDSIDEISUSE: Is Use").
                     setSize(5);
      third_side_blk.addField("ITEM1_SECOND_REMARK").
                     setDbName("SECOND_REMARK").
                     setInsertable().
                     setHidden().
                     setLabel("THIRDSIDEITEM1THIRDREMARK: Third Remark").
                     setSize(60).  
                     setHeight(3);
      third_side_blk.setView("THIRD_SIDE");
      third_side_blk.defineCommand("THIRD_SIDE_API","New__,Modify__,Remove__");
      third_side_blk.setMasterBlock(headblk);
      third_side_set = third_side_blk.getASPRowSet();
      third_side_bar = mgr.newASPCommandBar(third_side_blk);
      third_side_bar.defineCommand(third_side_bar.OKFIND, "okFindITEM2");
      third_side_bar.defineCommand(third_side_bar.NEWROW, "newRowITEM2");
      third_side_tbl = mgr.newASPTable(third_side_blk);
      third_side_tbl.setTitle("THIRDSIDEITEMHEAD2: ThirdSide");
      third_side_tbl.enableRowSelect();
      third_side_tbl.setWrap();
      third_side_lay = third_side_blk.getASPBlockLayout();
      third_side_lay.setDefaultLayoutMode(third_side_lay.MULTIROW_LAYOUT);
      third_side_lay.setDataSpan("ITEM1_SECOND_REMARK", 5);
            
      second_account_blk = mgr.newASPBlock("ITEM4");
      second_account_blk.addField("ITEM3_OBJID").
                         setHidden().
                         setDbName("OBJID");
      second_account_blk.addField("ITEM3_OBJVERSION").
                         setHidden().
                         setDbName("OBJVERSION");
      second_account_blk.addField("ITEM3_PROJ_NO").
                         setDbName("PROJ_NO").
                         setHidden().
                         setMandatory().
                         setInsertable().
                         setLabel("SECONDACCOUNTITEM3PROJNO: Proj No").
                         setSize(50);
      second_account_blk.addField("ITEM3_CONTRACT_ID").
                         setDbName("CONTRACT_ID").
                         setMandatory().
                         setHidden().
                         setInsertable().
                         setLabel("SECONDACCOUNTITEM3CONTRACTID: Contract Id").
                         setSize(100);
      second_account_blk.addField("ACCOUNT_ID").
                         setMandatory().
                         setHidden().
                         setInsertable().
                         setLabel("SECONDACCOUNTACCOUNTID: Account Id").
                         setSize(30);
      second_account_blk.addField("ACCOUNT_NO").
                         setInsertable().
                         setMandatory().
                         setLabel("SECONDACCOUNTACCOUNTNO: Account No").
                         setSize(30);
      second_account_blk.addField("ITEM3_BANK_ID").
                         setDbName("BANK_ID").
                         setInsertable().
                         setHidden().  
                         setLabel("SECONDACCOUNTITEM3BANKID: Bank Id").
                         setSize(30);
      second_account_blk.addField("ITEM3_BANK_NAME").
                         setMandatory().
                         setDbName("BANK_NAME").
                         setInsertable().
                         setLabel("SECONDACCOUNTITEM3BANKNAME: Bank Name").
                         setSize(30);
      second_account_blk.addField("ITEM3_IS_USE").
                         setDbName("IS_USE").
                         setInsertable().
                         setHidden().
                         setLabel("SECONDACCOUNTITEM3ISUSE: Is Use").
                         setSize(100);
      second_account_blk.addField("ACCOUNT_REMARK").
                         setInsertable().
                         setLabel("SECONDACCOUNTACCOUNTREMARK: Account Remark").
                         setSize(140).
                         setHeight(3);  
      second_account_blk.setView("SECOND_ACCOUNT");
      second_account_blk.defineCommand("SECOND_ACCOUNT_API","New__,Modify__,Remove__");
      second_account_blk.setMasterBlock(headblk);
      second_account_set = second_account_blk.getASPRowSet();
      second_account_bar = mgr.newASPCommandBar(second_account_blk);
      second_account_bar.defineCommand(second_account_bar.OKFIND, "okFindITEM4");
      second_account_bar.defineCommand(second_account_bar.NEWROW, "newRowITEM4");
      second_account_tbl = mgr.newASPTable(second_account_blk);
      second_account_tbl.setTitle("SECONDACCOUNTITEMHEAD4: SecondAccount");
      second_account_tbl.enableRowSelect();
      second_account_tbl.setWrap();
      second_account_lay = second_account_blk.getASPBlockLayout();
      second_account_lay.setDefaultLayoutMode(second_account_lay.MULTIROW_LAYOUT);
      second_account_lay.setDataSpan("ACCOUNT_REMARK", 5);
      
      contract_detain_class_blk = mgr.newASPBlock("DETAINCLASS");
      contract_detain_class_blk.addField("DETAINCLASS_OBJID").
                                setDbName("OBJID").
                                setHidden();
      contract_detain_class_blk.addField("DETAINCLASS_OBJVERSION").
                                setDbName("OBJVERSION").
                                setHidden();
      contract_detain_class_blk.addField("DETAINCLASS_PROJ_NO").
                                setDbName("PROJ_NO").
                                setHidden().
                                setMandatory().
                                setInsertable().
                                setLabel("DETAINCLASSPROJNO: Proj No").
                                setSize(50);
      contract_detain_class_blk.addField("DETAINCLASS_CONTRACT_ID").
                                setDbName("CONTRACT_ID").
                                setMandatory().
                                setHidden().
                                setInsertable().
                                setLabel("DETAINCLASSCONTRACTID: Contract Id").
                                setSize(100);
      contract_detain_class_blk.addField("DETAIN_NO").
                                setMandatory().  
                                setDynamicLOV("CONTRACT_DETAIN_CLASS").  
                                setInsertable().       
                                setCustomValidation("CONTRACT_ID,PROJ_NO,DETAIN_NO", "DETAIN_NAME,DETAIN_FLAG,SCALE").
                                setLabel("CONTRACTDETAINCLASSDETAINNO: Detain No").
                                setSize(30); 
      contract_detain_class_blk.addField("DETAIN_NAME").
                                setInsertable().
                                setLabel("CONTRACTDETAINCLASSDETAINNAME: Detain Name").
                                setSize(30);
      contract_detain_class_blk.addField("DETAIN_FLAG").
                                setHidden(). 
                                setCheckBox("FALSE,TRUE").
                                setInsertable().  
                                setLabel("CONTRACTDETAINCLASSDETAINFLAG: Detain Flag").
                                setSize(30);
      contract_detain_class_blk.addField("SCALE").
                                setInsertable().
                                setLabel("CONTRACTDETAINCLASSSCALE: Scale").
                                setSize(30);
      contract_detain_class_blk.addField("PAGE_NAME").
                                setInsertable().
                                setHidden().
                                setLabel("CONTRACTDETAINCLASSPAGENAME: Page Name").
                                setSize(30);
      contract_detain_class_blk.addField("DETAINCLASS_LU_NAME").
                                setInsertable().
                                setDbName("LU_NAME").
                                setHidden().
                                setLabel("CONTRACTDETAINCLASSLUNAME: Lu Name").
                                setSize(30);
      contract_detain_class_blk.addField("VIEW_NAME").
                                setInsertable().
                                setHidden().
                                setLabel("CONTRACTDETAINCLASSVIEWNAME: View Name").
                                setSize(30);  
      contract_detain_class_blk.setView("PROJECT_CONTRACT_DETAIN");
      contract_detain_class_blk.defineCommand("PROJECT_CONTRACT_DETAIN_API","New__,Modify__,Remove__");
      contract_detain_class_set = contract_detain_class_blk.getASPRowSet();
      contract_detain_class_bar = mgr.newASPCommandBar(contract_detain_class_blk);
      contract_detain_class_bar.defineCommand(contract_detain_class_bar.OKFIND, "okFindDetainClass");
      contract_detain_class_bar.defineCommand(contract_detain_class_bar.NEWROW, "newRowDetainClass");
      contract_detain_class_tbl = mgr.newASPTable(contract_detain_class_blk);    
      contract_detain_class_tbl.setTitle("CONTRACTDETAINCLASSTBLcontract_detain_class_: Contract Detain Classs");
      contract_detain_class_tbl.enableRowSelect();
      contract_detain_class_tbl.setWrap();
      contract_detain_class_lay = contract_detain_class_blk.getASPBlockLayout();
      contract_detain_class_lay.setDefaultLayoutMode(contract_detain_class_lay.MULTIROW_LAYOUT);
      
      
      contract_variation_blk = mgr.newASPBlock("ITEM5");
      contract_variation_blk.addField("ITEM5_OBJID").
                                setDbName("OBJID").
                                setHidden();
      contract_variation_blk.addField("ITEM5_OBJVERSION").
                                setDbName("OBJVERSION").
                                setHidden();
      contract_variation_blk.addField("ITEM5_PROJ_NO").
                                setDbName("PROJ_NO").
                                setHidden().
                                setMandatory().
                                setLabel("CONTRACTVARIATIONPROJNO: Proj No").
                                setSize(50);
      contract_variation_blk.addField("ITEM5_CONTRACT_ID").
                                setDbName("CONTRACT_ID").
                                setMandatory().
                                setHidden().
                                setInsertable().
                                setLabel("CONTRACTVARIATIONCONTRACTID: Contract Id").
                                setSize(100);
      contract_variation_blk.addField("CONTRACT_VAR_NO","Number").
                             setInsertable().
                             setHidden().      
                             setLabel("CONTRACTVARIATIONOTHCONTRACTVARNO: Contract Var No").
                             setSize(30);
      contract_variation_blk.addField("ITEM5_CHANGE_CONTRACT_ID").
                             setDbName("CHANGE_CONTRACT_ID").
                             setLabel("CONTRACTVARIATIONCHANGECONTRACTID: Change Contract Id").
                             setSize(30);
      contract_variation_blk.addField("ITEM5_CONTRACT_VAR_DESC").
                             setDbName("CONTRACT_VAR_DESC").
                             setLabel("CONTRACTVARIATIONCONTRACTVARDESC: Contract Var Desc").
                             setSize(30);
      contract_variation_blk.addField("ITEM5_CHANGING_PRICE").
                             setFunction("CONTRACT_VARIATION_API.Cal_VR_Total(:PROJ_NO, :CONTRACT_ID,:CONTRACT_VAR_NO)").
                             setLabel("CONTRACTVARIATIONCHANGINGPRICE: Changing Price").
                             setSize(30);
      contract_variation_blk.setView("CONTRACT_VARIATION");
      contract_variation_blk.defineCommand("CONTRACT_VARIATION_API","");
      contract_variation_blk.setMasterBlock(headblk);
      contract_variation_set = contract_variation_blk.getASPRowSet();
      contract_variation_bar = mgr.newASPCommandBar(contract_variation_blk);
      contract_variation_bar.defineCommand(contract_variation_bar.OKFIND, "okFindITEM5");
      contract_variation_tbl = mgr.newASPTable(contract_variation_blk);    
      contract_variation_tbl.setTitle("CONTRACT_VARIATIONTBLcontract_variation: Contract Variation");
      contract_variation_tbl.enableRowSelect();
      contract_variation_tbl.setWrap();
      contract_variation_lay = contract_variation_blk.getASPBlockLayout();
      contract_variation_lay.setDefaultLayoutMode(contract_variation_lay.MULTIROW_LAYOUT);
          
      
      tabs = mgr.newASPTabContainer();
      tabs.addTab(mgr.translate("CONTRACTLINETAB: Contract Line" ), "javascript:commandSet('MAIN.activateContractLine', '')");
      tabs.addTab(mgr.translate("CONTRACTTHIRDTAB: Contract Third" ), "javascript:commandSet('MAIN.activateThird', '')");
      tabs.addTab(mgr.translate("CONTRACTSECONDACCOUNTTAB: Second Account" ), "javascript:commandSet('MAIN.activateSedcondAccount', '')");
      tabs.addTab(mgr.translate("PROJECTCONTRACTDETAINTAB: Contract Detain Class" ), "javascript:commandSet('MAIN.activateDetainClass', '')");
      tabs.addTab(mgr.translate("CONTRACTVARIATIONTAB: Contract Variation" ), "javascript:commandSet('MAIN.activateContractVariation', '')");
      headbar.addCustomCommand("activateContractLine", "");
      headbar.addCustomCommand("activateThird", "");
      headbar.addCustomCommand("activateSedcondAccount", "");
      headbar.addCustomCommand("activateDetainClass", "");
      headbar.addCustomCommand("activateContractVariation", "");
   }  

   public void activateContractLine()
   {
      tabs.setActiveTab(1);
      okFindITEM1();
   }
   public void activateThird()
   {
      tabs.setActiveTab(2);
      okFindITEM2();
   }
   public void activateSedcondAccount()
   {
      tabs.setActiveTab(3);
      okFindITEM4();
   }
   public void activateDetainClass()
   {
      tabs.setActiveTab(4);
      okFindDetainClass();   
   }
   public void activateContractVariation()
   {
      tabs.setActiveTab(5);
      okFindITEM5();   
   }
   
   public void adjust() throws FndException
   {
      super.adjust();
      if(headlay.isMultirowLayout()){
         headset.storeSelections();
         ASPBuffer selected_fields=headset.getSelectedRows("OBJSTATE");
         for(int i=0;i<selected_fields.countItems();i++){
             ASPBuffer subBuff = selected_fields.getBufferAt(i);
             String state=subBuff.getValueAt(0);
             if( "Closed".equals(state) || "Checked".equals(state) ){
                 headbar.disableCommand(headbar.DELETE);
                 headbar.disableCommand(headbar.EDITROW);   
            }
         }  
      } else {
         if(headset.countRows()>0){
          String state = headset.getValue("OBJSTATE");
          if( headlay.isSingleLayout() && ("Closed".equals(state) || "Checked".equals(state))){ 
                headbar.disableCommand(headbar.DELETE);
                headbar.disableCommand(headbar.EDITROW);   
              project_contract_item_bar.disableCommand( project_contract_item_bar.DELETE );
              project_contract_item_bar.disableCommand(project_contract_item_bar.NEWROW);
              project_contract_item_bar.disableCommand( project_contract_item_bar.EDITROW );
              third_side_bar.disableCommand( third_side_bar.DELETE );
              third_side_bar.disableCommand( third_side_bar.EDITROW );  
              third_side_bar.disableCommand(third_side_bar.NEWROW);  
              second_account_bar.disableCommand( second_account_bar.DELETE );
              second_account_bar.disableCommand( second_account_bar.EDITROW );
              second_account_bar.disableCommand(second_account_bar.NEWROW); 
              
          }  
      }
      }
      // fill function body
   }

   public void validate()
   {
       ASPManager mgr = getASPManager();  
       ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
       ASPCommand cmd;
       String val = mgr.readValue("VALIDATE");    
       float tempValue = 0;
       
       if ("PRICE".equals(val)) {         
         tempValue = ((mgr.readValue("PRICE")==null)?0:Float.parseFloat(mgr.readValue("PRICE")))*((mgr.readValue("ORIGINAL_QTY")==null)?0:Float.parseFloat(mgr.readValue("ORIGINAL_QTY")));
         java.text.DecimalFormat df = new java.text.DecimalFormat("#0.00"); 
         String strValue = df.format(tempValue);     
         mgr.responseWrite(String.valueOf(strValue)+"^");
       }
       else if("ORIGINAL_QTY".equals(val)){
         tempValue = ((mgr.readValue("PRICE")==null)?0:Float.parseFloat(mgr.readValue("PRICE")))*((mgr.readValue("ORIGINAL_QTY")==null)?0:Float.parseFloat(mgr.readValue("ORIGINAL_QTY")));
         java.text.DecimalFormat df = new java.text.DecimalFormat("#0.00"); 
         String strValue = df.format(tempValue);  
         mgr.responseWrite(String.valueOf(strValue)+"^");  
       }else if("ITEM_TYPE".equals(val)){
           if("FOLDER".equals(mgr.readValue("ITEM_TYPE"))){
             String txt =  "" + "^" +  "" + "^" +   "" + "^" +   "" + "^" +   "" + "^" +   "" + "^";
             mgr.responseWrite(txt);
           }  
       }        
       else if("DETAIN_NO".equals(val)){    
          String proj_no = mgr.readValue("PROJ_NO"); 
          String contract_id = mgr.readValue("CONTRACT_ID");
          cmd = trans.addCustomFunction("DETAINNAME", 
                "PROJECT_CONTRACT_DETAIN_API.Get_Detain_Name", "DETAIN_NAME");
          cmd.addParameter("ITEM0_PROJ_NO",proj_no); 
          cmd.addParameter("ITEM0_CONTRACT_ID",contract_id);
          cmd.addParameter("DETAIN_NO");     
          
          cmd = trans.addCustomFunction("DETAINFLAG", 
                "PROJECT_CONTRACT_DETAIN_API.Get_Detain_Flag", "DETAIN_FLAG");
          cmd.addParameter("ITEM0_PROJ_NO",proj_no);    
          cmd.addParameter("ITEM0_CONTRACT_ID",contract_id);
          cmd.addParameter("DETAIN_NO");
          
          cmd = trans.addCustomFunction("SCALE", 
                "PROJECT_CONTRACT_DETAIN_API.Get_Scale", "SCALE");
          cmd.addParameter("ITEM0_PROJ_NO",proj_no);
          cmd.addParameter("ITEM0_CONTRACT_ID",contract_id);
          cmd.addParameter("DETAIN_NO");  
          
          trans = mgr.validate(trans);   
         String detain_name = trans.getValue("DETAINNAME/DATA/DETAIN_NAME");
         String detain_flag = trans.getValue("DETAINFLAG/DATA/DETAIN_FLAG");
         String scale = trans.getValue("SCALE/DATA/SCALE");
         trans.clear();
         cmd.clear();        
         String txt = ((mgr.isEmpty(detain_name)) ? "" : detain_name) + "^" + ((mgr.isEmpty(detain_flag)) ? "FALSE" : detain_flag) + "^" + ((mgr.isEmpty(scale)) ? "1" : scale) + "^";
         mgr.responseWrite(txt);   
      }              
       mgr.endResponse();    
   }
   //-----------------------------------------------------------------------------
   //------------------------  Presentation functions  ---------------------------
   //-----------------------------------------------------------------------------
   public void  printReport() throws FndException, UnsupportedEncodingException
   {
    ASPManager mgr = getASPManager();
    ASPConfig cfg = getASPConfig();
    String URL=cfg.getParameter("APPLICATION/RUNQIAN/SERVER_URL");
    
    if (headlay.isMultirowLayout())
       headset.goTo(headset.getRowSelected());
    if (headset.countRows()>0 )
          {   
             String class_no = headset.getValue("CLASS_NO");
             String proj_no = headset.getValue("PROJ_NO");
             String contract_id = headset.getValue("CONTRACT_ID");
             if("WZ".equals(class_no) || "SB".equals(class_no)){
              appendDirtyJavaScript("window.open('"+URL+"/showReport.jsp?raq=RptContractContactMat.raq&proj_no="+proj_no+"&contract_id="+contract_id
                + "','_blank','height=600, width=780, top=200, left=350, toolbar=no, menubar=no, scrollbars=yes, resizable=yes,location=no, status=no');");                                
             }else{
                appendDirtyJavaScript("window.open('"+URL+"/showReport.jsp?raq=RptProjectContract.raq&proj_no="+proj_no+"&contract_id="+contract_id
                      + "','_blank','height=600, width=780, top=200, left=350, toolbar=no, menubar=no, scrollbars=yes, resizable=yes,location=no, status=no');");                                
             }
         }
   }   
   //add by lhh 20141205 
   protected String getImageFieldTag(ASPField imageField, ASPRowSet rowset, int rowNum) throws FndException
   {
      ASPManager mgr = getASPManager();
      String imgSrc = mgr.getASPConfig().getImagesLocation();

      if (rowset.countRows() > 0 && "VIEW_REF_FILE".equals(imageField.getName()))
      {
         if ("TRUE".equals(rowset.getValueAt(rowNum, "EXIST_DOC_REF"))) {
            imgSrc += "folder.gif";
            return "<img src=\"" + imgSrc + "\" height=\"16\" width=\"16\" border=\"0\">";
         }
         else
         {
            return "";
         }
      }
      return "";
   }
   
   protected String getDescription()
   {
      return "PROJECTCONTRACTDESC: Project Contract";
   }


   protected String getTitle()
   {
      return "PROJECTCONTRACTTITLE: Project Contract";
   }


   protected void printContents() throws FndException
   {
      super.printContents();

      ASPManager mgr = getASPManager();    
      if (headlay.isVisible())
          appendToHTML(headlay.show());
      else
      {
         headlay.setLayoutMode(headlay.CUSTOM_LAYOUT);
         appendToHTML(headlay.show());
      }       
      if((headlay.isSingleLayout() || headlay.isCustomLayout()) && headset.countRows() > 0 ){
          appendToHTML(tabs.showTabsInit());      
          if (tabs.getActiveTab() == 1)
              appendToHTML(project_contract_item_lay.show());
          if (tabs.getActiveTab() == 2)
              appendToHTML(third_side_lay.show());
          if (tabs.getActiveTab() == 3)  
              appendToHTML(second_account_lay.show());
          if (tabs.getActiveTab() == 4)  
             appendToHTML(contract_detain_class_lay.show());
          if (tabs.getActiveTab() == 5)  
             appendToHTML(contract_variation_lay.show());
          appendToHTML(tabs.showTabsFinish());      
      }    
   }
   //--------------------------  Added in new template  --------------------------
   //--------------  Return blk connected with workflow functions  ---------------
   //-----------------------------------------------------------------------------

   protected ASPBlock getBizWfBlock()
   {
      return headblk;
   }
}
