/*
*                 IFS Research & Development
*
*  This program is protected by copyright law and by international
*  conventions. All licensing, renting, lending or copying (including
*  for private use), and all other use of the program, which is not
*  expressively permitted by IFS Research & Development (IFS), is a
*  violation of the rights of IFS. Such violations will be reported to the
*  appropriate authorities.
*
*  VIOLATIONS OF ANY COPYRIGHT IS PUNISHABLE BY LAW AND CAN LEAD
*  TO UP TO TWO YEARS OF IMPRISONMENT AND LIABILITY TO PAY DAMAGES.
* ----------------------------------------------------------------------------
* File                          :
* Description                   :
* Notes                         :
* Other Programs Called :
* ----------------------------------------------------------------------------
* Modified    : Automatically generated by IFS/Design
* ----------------------------------------------------------------------------
*/

//-----------------------------------------------------------------------------
//-----------------------------   Package def  ------------------------------
//-----------------------------------------------------------------------------

package ifs.matmaw;
//-----------------------------------------------------------------------------
//-----------------------------   Import def  ------------------------------
//-----------------------------------------------------------------------------

import java.io.UnsupportedEncodingException;

import ifs.fnd.asp.*;
import ifs.fnd.buffer.*;
import ifs.fnd.service.*;
import ifs.fnd.*;

//-----------------------------------------------------------------------------
//-----------------------------   Class def  ------------------------------
//-----------------------------------------------------------------------------

public class MatArrive extends ASPPageProvider
{

   //-----------------------------------------------------------------------------
   //---------- Static constants ------------------------------------------------
   //-----------------------------------------------------------------------------

   public static boolean DEBUG = Util.isDebugEnabled("ifs.matmaw.MatArrive");

   //-----------------------------------------------------------------------------
   //---------- Header Instances created on page creation --------
   //-----------------------------------------------------------------------------

   private ASPBlock headblk;
   private ASPRowSet headset;
   private ASPCommandBar headbar;
   private ASPTable headtbl;
   private ASPBlockLayout headlay;

   //-----------------------------------------------------------------------------
   //---------- Item Instances created on page creation --------
   //-----------------------------------------------------------------------------

   private ASPBlock mat_arrive_line_blk;
   private ASPRowSet mat_arrive_line_set;
   private ASPCommandBar mat_arrive_line_bar;
   private ASPTable mat_arrive_line_tbl;
   private ASPBlockLayout mat_arrive_line_lay;


   //-----------------------------------------------------------------------------
   //------------------------  Construction  ---------------------------
   //-----------------------------------------------------------------------------

   public  MatArrive (ASPManager mgr, String page_path)
   {
      super(mgr, page_path);
   }

   public void run() throws FndException
   {
      super.run();

      ASPManager mgr = getASPManager();

      if( mgr.commandBarActivated() )
         eval(mgr.commandBarFunction());
      else if ( !mgr.isEmpty(mgr.getQueryStringValue("VALIDATE")) )
         validate();   
      else if(mgr.dataTransfered())
         okFind();
      else if( !mgr.isEmpty(mgr.getQueryStringValue("SEARCH")) )
         okFind();
      else if( !mgr.isEmpty(mgr.getQueryStringValue("ARRIVE_ID")) )
         okFind();
      else 
         okFind();
      adjust();
   }
   
   
   public void validate()
   {
      ASPManager mgr=getASPManager();
      ASPTransactionBuffer trans0=mgr.newASPTransactionBuffer();
      ASPCommand cmd0;
      String str=mgr.readValue("VALIDATE");
    
      if ("ITEM_NO".equals(str)) {

         cmd0 = trans0.addCustomFunction("MAT_NO","PROJECT_CONTRACT_ITEM_API.GET_MAT_NO","MAT_NO");
         cmd0.addParameter("PROJ_NO");
         cmd0.addParameter("CONTRACT_ID");
         cmd0.addParameter("ITEM_NO");
         cmd0 = trans0.addCustomFunction("ITEM_DESC","PROJECT_CONTRACT_ITEM_API.GET_ITEM_DESC","ITEM_DESC");
         cmd0.addParameter("PROJ_NO");
         cmd0.addParameter("CONTRACT_ID");
         cmd0.addParameter("ITEM_NO");
         cmd0 = trans0.addCustomFunction("UNIT_CODE","PROJECT_CONTRACT_ITEM_API.Get_Item_Unit","UNIT_CODE");
         cmd0.addParameter("PROJ_NO");
         cmd0.addParameter("CONTRACT_ID");
         cmd0.addParameter("ITEM_NO");

         trans0 = mgr.validate(trans0);

         String MAT_NO     = trans0.getValue("MAT_NO/DATA/MAT_NO");
         String ITEM_DESC     = trans0.getValue("ITEM_DESC/DATA/ITEM_DESC");
         String UNIT_CODE     = trans0.getValue("UNIT_CODE/DATA/UNIT_CODE");

         MAT_NO     = mgr.isEmpty(MAT_NO    )? ""  : MAT_NO    ;
         ITEM_DESC     = mgr.isEmpty(ITEM_DESC    )? ""  : ITEM_DESC    ;
         UNIT_CODE     = mgr.isEmpty(UNIT_CODE    )? ""  : UNIT_CODE    ;
         
         mgr.responseWrite(ITEM_DESC + "^"+ MAT_NO + "^"+ UNIT_CODE + "^");
      }
      
      mgr.endResponse();
   }
   
   
   //-----------------------------------------------------------------------------
   //------------------------  Command Bar functions  ---------------------------
   //-----------------------------------------------------------------------------

   public void okFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      mgr.createSearchURL(headblk);
      q = trans.addQuery(headblk);
      q.includeMeta("ALL");
      if(mgr.dataTransfered())
         q.addOrCondition(mgr.getTransferedData());
      mgr.querySubmit(trans,headblk);
      if (  headset.countRows() == 0 )
      {
         mgr.showAlert("MATARRIVENODATA: No data found.");
         headset.clear();
      }
      eval( mat_arrive_line_set.syncItemSets() );
   }



   public void countFind()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;

      q = trans.addQuery(headblk);
      q.setSelectList("to_char(count(*)) N");
      mgr.submit(trans);
      headlay.setCountValue(toInt(headset.getValue("N")));
      headset.clear();
   }



   public void newRow()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPBuffer data;
      ASPCommand cmd;

      cmd = trans.addEmptyCommand("HEAD","MAT_ARRIVE_API.New__",headblk);
      cmd.setOption("ACTION","PREPARE");
      trans = mgr.perform(trans);
      data = trans.getBuffer("HEAD/DATA");
      headset.addRow(data);
   }


   //-----------------------------------------------------------------------------
   //------------------------  Item block cmd bar functions  ---------------------------
   //-----------------------------------------------------------------------------


   public void okFindITEM1()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPQuery q;
      int headrowno;

      q = trans.addQuery(mat_arrive_line_blk);
      q.addWhereCondition("PROJ_NO = ? AND ARRIVE_ID = ?");
      q.addParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      q.addParameter("ARRIVE_ID", headset.getValue("ARRIVE_ID"));
      q.includeMeta("ALL");
      headrowno = headset.getCurrentRowNo();
      mgr.querySubmit(trans,mat_arrive_line_blk);
      headset.goTo(headrowno);
   }
   public void newRowITEM1()
   {
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      ASPBuffer data;

      
      cmd = trans.addEmptyCommand("ITEM1","MAT_ARRIVE_LINE_API.New__",mat_arrive_line_blk);
      cmd.setOption("ACTION","PREPARE");
      cmd.setParameter("ITEM0_PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ITEM0_ARRIVE_ID", headset.getValue("ARRIVE_ID"));
      cmd.setParameter("ITEM0_CONTRACT_ID", headset.getValue("CONTRACT_ID"));
      trans = mgr.perform(trans);
      data = trans.getBuffer("ITEM1/DATA");
      mat_arrive_line_set.addRow(data);
   }

   //-----------------------------------------------------------------------------
   //------------------------  Predefines Head ---------------------------
   //-----------------------------------------------------------------------------

   public void preDefine()
   {
      ASPManager mgr = getASPManager();

      headblk = mgr.newASPBlock("MAIN");
      headblk.addField("OBJID").
              setHidden();
      headblk.addField("OBJVERSION").
              setHidden();
      headblk.addField("ARRIVE_ID").
              setMandatory().
              setInsertable().
              setLabel("MATARRIVEARRIVEID: Arrive Id").
              setSize(20);
      headblk.addField("PROJ_NO").
              setMandatory().
              setInsertable().
              setDynamicLOV("GENERAL_PROJECT").
              setLabel("MATARRIVEPROJNO: Proj No").
              setSize(20);
      headblk.addField("PROJ_DESC").
               setFunction("GENERAL_PROJECT_API.GET_PROJ_DESC (:PROJ_NO)").
               setLabel("MATARRIVEPROJDESC: Proj Desc").
               setReadOnly().
               setSize(30);
      mgr.getASPField("PROJ_NO").setValidation("PROJ_DESC");
      headblk.addField("CONTRACT_ID").
              setInsertable().
              setMandatory().
//              setHidden().
              setDynamicLOV("PROJECT_CONTRACT_LOV","PROJ_NO").
              setLOVProperty("WHERE", "CLASS_NO IN ('SB','WZ')").
              setLabel("MATARRIVECONTRACTID: Contract Id").
              setSize(20);
      headblk.addField("CONTRACT_DESC").
              setFunction("PROJECT_CONTRACT_API.GET_CONTRACT_DESC ( :PROJ_NO,:CONTRACT_ID)").
              setLabel("MATARRIVECONTRACTDESC: Contract Desc").
              setReadOnly().
//              setHidden().
              setSize(30);
      mgr.getASPField("CONTRACT_ID").setValidation("CONTRACT_DESC");
      headblk.addField("MAT_TRANS_METHOD").
              enumerateValues("Mat_Trans_Method_API").
              setSelectBox().
              setMandatory().
              setInsertable().
              setLabel("MATARRIVEMATTRANSMETHOD: Mat Trans Method").
              setSize(20);

      headblk.addField("PRO_ORG").
              setInsertable().
              setLabel("MATARRIVEPROORG: Pro Org").
              setSize(20);
//add by lhh 20141103
      headblk.addField("VIEW_REF_FILE").
           setReadOnly().
            unsetQueryable().
            setFunction("''").
           setLabel("MATARRIVEVIEWFILE: View File").
           setHyperlink( mgr.getApplicationPath()
              + "/" + mgr.getConfigParameter("DOCMAW/DOC_REF_URL")
              + "?VIEW=" + mgr.URLEncode("MAT_ARRIVE"), "OBJID", "NEWWIN").
           setAsImageField();
       headblk.addField("LU_NAME").
             setHidden();
       headblk.addField("KEY_REF").
             setHidden();
       headblk.addField("EXIST_DOC_REF").
             setHidden().
             setCheckBox("FALSE,TRUE").
             setFunction("Doc_Reference_Object_API.Exist_Obj_Reference(:LU_NAME, :KEY_REF)").
             setSize(5);
//add by lhh end       
      headblk.addField("STATUS").
//              setInsertable().
              setReadOnly().
              setLabel("MATARRIVESTATUS: Status").
              setSize(20);
      
      headblk.addField("ARRIVE_TIME","Date","yyyy-MM-dd").
              setInsertable().
              setLabel("MATARRIVEARRIVETIME: Arrive Time").
              setSize(20);
      headblk.addField("TRANS_ORG").
              setInsertable().
              setLabel("MATARRIVETRANSORG: Trans Org").
              setSize(20);
      headblk.addField("TRANS_NO").
              setInsertable().
              setLabel("MATARRIVETRANSNO: Trans No").
              setSize(20);
//add by lhh 20141126
      headblk.addField("UNIT_NO").
              setInsertable().
              setLabel("MATARRIVEUNITNO: Unit No").
              setSize(20);
      headblk.addField("GW").
              setInsertable().
              setLabel("MATARRIVEGW: Gw").
              setSize(20);
      headblk.addField("VOLUME").
              setInsertable().
              setLabel("MATARRIVEVOLUME: Volume").
              setSize(20);
//add by lhh end     
      headblk.addField("LOT").
              setInsertable().
              setLabel("MATARRIVELOT: Lot").
              setSize(20);
      headblk.addField("PACKAGE_QTY","Number").
              setInsertable().
              setLabel("MATARRIVEPACKAGEQTY: Package Qty").
              setSize(20);
      headblk.addField("NUDE_QTY","Number"). 
              setInsertable().
              setLabel("MATARRIVENUDEQTY: Nude Qty").
              setSize(20);
      headblk.addField("STORE_PLACE").
              setInsertable().
              setLabel("MATARRIVESTOREPLACE: Store Place").
              setHeight(4).
              setSize(50);

      headblk.addField("MAT_PACK_STATUS").
              setInsertable().
              setLabel("MATARRIVEMATPACKSTATUS: Mat Pack Status").
              setHeight(4).
              setSize(50);

      headblk.addField("ARRIVE_MSG").
              setInsertable().
              setLabel("MATARRIVEARRIVEMSG: Arrive Msg").
              setHeight(4).
              setSize(50);
//      headblk.addField("GENERAL_PROJECT_PROJ_DESC").
//              setFunction("GENERAL_PROJECT_API.GET_PROJ_DESC ( PROJ_NO)").
//              setLabel("MATARRIVEGENERALPROJECTPROJDESC: General Project Proj Desc").
//              setSize(30);
      headblk.addField("CREATE_PERSON").
              setInsertable().
              setDynamicLOV("PERSON_INFO").
              setLabel("MATARRIVECREATEPERSON: Create Person").
              setSize(20);
      headblk.addField("PERSON_NAME").
              setFunction("PERSON_INFO_API.GET_NAME (:CREATE_PERSON)").
              setLabel("MATARRIVEPERSONINFONAME: Person Name").
              setReadOnly().
              setSize(30);
      mgr.getASPField("CREATE_PERSON").setValidation("PERSON_NAME");
      headblk.addField("CREATE_TIME","Date","yyyy-MM-dd").
              setInsertable().
              setLabel("MATARRIVECREATETIME: Create Time").
              setSize(20);
      
      headblk.setView("MAT_ARRIVE");
      headblk.defineCommand("MAT_ARRIVE_API","New__,Modify__,Remove__");
      headset = headblk.getASPRowSet();
      headbar = mgr.newASPCommandBar(headblk);
      headtbl = mgr.newASPTable(headblk);
      headtbl.setTitle("MATARRIVETBLHEAD: Mat Arrives");
      headtbl.enableRowSelect();
      headtbl.setWrap();
      headlay = headblk.getASPBlockLayout();
      headlay.setDefaultLayoutMode(headlay.MULTIROW_LAYOUT);
      headbar.addCustomCommand("makeAccept", "MATARRIVEMAKEACCEPT: Make Accept");
      headbar.addCommandValidConditions("makeAccept", "STATUS", "Enable", "已创建");
      headbar.addCustomCommand("makeClose", "MATARRIVEMAKECLOSE: Make Close");
      headbar.addCommandValidConditions("makeClose", "STATUS", "Disable", "已关闭");
      headbar.addCustomCommand("printReport", "MATARRIVEPRINTREPORT: Print Report...");
      headlay.setSimple("PROJ_DESC");
      headlay.setSimple("CONTRACT_DESC");
      headlay.setSimple("PERSON_NAME");
//      headlay.setDataSpan("STORE_PLACE", 5);
//    headlay.setDataSpan("STATUS", 5);
    headlay.setDataSpan("ARRIVE_MSG", 5);
 


      mat_arrive_line_blk = mgr.newASPBlock("ITEM1");
      mat_arrive_line_blk.addField("ITEM0_OBJID").
                          setHidden().
                          setDbName("OBJID");
      mat_arrive_line_blk.addField("ITEM0_OBJVERSION").
                          setHidden().
                          setDbName("OBJVERSION");
      mat_arrive_line_blk.addField("ITEM0_PROJ_NO").
                          setDbName("PROJ_NO").
                          setMandatory().
                          setInsertable().
                          setHidden().
                          setLabel("MATARRIVELINEITEM0PROJNO: Proj No").
                          setSize(50);
      mat_arrive_line_blk.addField("ITEM0_ARRIVE_ID").
                          setDbName("ARRIVE_ID").
                          setMandatory().
                          setInsertable().
                          setHidden().
                          setLabel("MATARRIVELINEITEM0ARRIVEID: Arrive Id").
                          setSize(50);
      mat_arrive_line_blk.addField("ARRIVE_LINE_NO").
//                          setMandatory().
                          setReadOnly().
//                          setInsertable().
                          setLabel("MATARRIVELINEARRIVELINENO: Arrive Line No").
                          setSize(20);

      mat_arrive_line_blk.addField("ITEM0_CONTRACT_ID").
                          setDbName("CONTRACT_ID").
                          setDynamicLOV("PROJECT_CONTRACT_LOV","PROJ_NO").
                          setInsertable().
                          setHidden().
                          setLabel("MATARRIVELINEITEM0CONTRACTID: Contract Id").
                          setSize(20);

      mat_arrive_line_blk.addField("ITEM0_CONTRACT_DESC").
                           setFunction("PROJECT_CONTRACT_API.GET_CONTRACT_DESC ( :PROJ_NO,:ITEM0_CONTRACT_ID)").
                           setLabel("MATARRIVECONTRACTDESC: Contract Desc").
                           setReadOnly().
                           setHidden().
                           setSize(30);
      mgr.getASPField("ITEM0_CONTRACT_ID").setValidation("ITEM0_CONTRACT_DESC");
      mat_arrive_line_blk.addField("ITEM_NO").
                          setInsertable().
                          setLabel("MATARRIVELINEITEMNO: Item No").
                          setDynamicLOV("PROJECT_CONTRACT_ITEM","PROJ_NO,CONTRACT_ID").
                          setCustomValidation("PROJ_NO,CONTRACT_ID,ITEM_NO", "ITEM_DESC,MAT_NO,UNIT_CODE").
                          setSize(20);

      mat_arrive_line_blk.addField("ITEM_DESC").
                          setFunction("PROJECT_CONTRACT_ITEM_API.GET_ITEM_DESC ( :PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
                          setLabel("MATARRIVELINEITEMDESC: Item Desc").
                          setReadOnly().
                          setSize(30);
      mgr.getASPField("ITEM_NO").setValidation("ITEM_DESC");

      mat_arrive_line_blk.addField("PACKAGE_NO").
                          setInsertable().
                          setLabel("MATARRIVELINEPACKAGENO: Package No").
                          setSize(20);
      

      mat_arrive_line_blk.addField("PACKAGE_NAME").
                          setInsertable().
                          setLabel("MATARRIVELINEPACKAGENAME: Package Name").
                          setSize(30);
      mat_arrive_line_blk.addField("MAT_NO").
                          setReadOnly().
                          setLabel("MATARRIVELINEMATNO: Mat No").
                          setFunction("PROJECT_CONTRACT_ITEM_API.GET_MAT_NO ( :PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
                          setSize(20);
//      mgr.getASPField("ITEM_NO").setValidation("MAT_NO");

//      mat_arrive_line_blk.addField("MAT_NO").
//                          setReadOnly().
//                          setLabel("MATARRIVELINEITEMNO: No").
//                          setFunction("PROJECT_CONTRACT_ITEM_API.GET_MAT_NO ( :PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
//                          setSize(20);
//      mgr.getASPField("ITEM_NO").setValidation("MAT_NO");
//
//      mat_arrive_line_blk.addField("MAT_NO").
//                          setReadOnly().
//                          setLabel("MATARRIVELINEITEMNO: No").
//                          setFunction("PROJECT_CONTRACT_ITEM_API.GET_MAT_NO ( :PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
//                          setSize(20);
//      mgr.getASPField("ITEM_NO").setValidation("MAT_NO");
//
//      mat_arrive_line_blk.addField("MAT_NO").
//                          setReadOnly().
//                          setLabel("MATARRIVELINEITEMNO: No").
//                          setFunction("PROJECT_CONTRACT_ITEM_API.GET_MAT_NO ( :PROJ_NO,:CONTRACT_ID,:ITEM_NO)").
//                          setSize(20);
//      mgr.getASPField("ITEM_NO").setValidation("MAT_NO");

      mat_arrive_line_blk.addField("GOODS_NAME").
                          setInsertable().
                          setLabel("MATARRIVELINEGOODSNAME: Goods Name").
                          setSize(30);
      
      mat_arrive_line_blk.addField("ARRIVE_QTY","Number").
                          setInsertable().
                          setLabel("MATARRIVELINEARRIVEQTY: Arrive Qty").
                          setSize(20);
      mat_arrive_line_blk.addField("UNIT_CODE").
                          setInsertable().
                          setDynamicLOV("ISO_UNIT").
                          setLabel("MATARRIVELINEUNITCODE: Unit Code").
                          setSize(20);
      mat_arrive_line_blk.addField("UNIT_DESC").
                          setReadOnly().
                          setLabel("MATARRIVELINEUNITDESC: Unit Desc").
                          setFunction("Iso_Unit_API.Get_Description(:UNIT_CODE)").
                          setSize(20);
      mgr.getASPField("UNIT_CODE").setValidation("UNIT_DESC");
      mat_arrive_line_blk.addField("IS_QTY_COMPLETE").
                          setInsertable().
                          setLabel("MATARRIVELINEISQTYCOMPLETE: Is Qty Complete").
                          setSize(20);
      mat_arrive_line_blk.addField("IS_DAMAGED").
                          setInsertable().
                          setLabel("MATARRIVELINEISDAMAGED: Is Damaged").
                          setSize(20);
      mat_arrive_line_blk.addField("IS_BLOCK_UP").
                          setInsertable().
                          setLabel("MATARRIVELINEISBLOCKUP: Is Block Up").
                          setSize(20);

      mat_arrive_line_blk.addField("SUPPLIER").
                          setInsertable().
                          setLabel("MATARRIVELINESUPPLIER: Supplier").
                          setSize(100);
      
      mat_arrive_line_blk.addField("PACKAGE_CASE").
                          setInsertable().
                          setLabel("MATARRIVELINEPACKAGECASE: Package Case").
                          setSize(100);
      mat_arrive_line_blk.addField("FRAGILE_DESC").
                          setInsertable().
                          setLabel("MATARRIVELINEFRAGILEDESC: Fragile Desc").
                          setSize(100);
      mat_arrive_line_blk.addField("LEFT_PROBLEMS").
                          setInsertable().
                          setLabel("MATARRIVELINELEFTPROBLEMS: Left Problems").
                          setSize(100);
      mat_arrive_line_blk.addField("NOTE").
                          setInsertable().
                          setHeight(4).
                          setLabel("MATARRIVELINENOTE: Note").
                          setSize(100);
      mat_arrive_line_blk.addField("ITEM0_CREATE_TIME","Date","yyyy-MM-dd").
                          setDbName("CREATE_TIME").
                          setInsertable().
                          setLabel("MATARRIVELINEITEM0CREATETIME: Create Time").
                          setSize(20);
      mat_arrive_line_blk.addField("ITEM0_CREATE_PERSON").
                          setDbName("CREATE_PERSON").
                          setInsertable().
                          setDynamicLOV("PERSON_INFO").
                          setLabel("MATARRIVELINEITEM0CREATEPERSON: Create Person").
                          setSize(20);
//      mat_arrive_line_blk.addField("ITEM0_GENERAL_PROJECT_PROJ_DESC").
//                          setFunction("GENERAL_PROJECT_API.GET_PROJ_DESC ( PROJ_NO)").
//                          setLabel("MATARRIVELINEITEM0GENERALPROJECTPROJDESC: General Project Proj Desc").
//                          setSize(30);
//      mat_arrive_line_blk.addField("ITEM0_PROJECT_CONTRACT_CONTRACT_DESC").
//                          setFunction("PROJECT_CONTRACT_API.GET_CONTRACT_DESC ( PROJ_NO,CONTRACT_ID)").
//                          setLabel("MATARRIVELINEITEM0PROJECTCONTRACTCONTRACTDESC: Project Contract Contract Desc").
//                          setSize(30);
      mat_arrive_line_blk.addField("ITEM0_PERSON_NAME").
                          setFunction("PERSON_INFO_API.GET_NAME ( :CREATE_PERSON)").
                          setLabel("MATARRIVELINEITEM0PERSONNAME: Person Name").
                          setReadOnly().
                          setSize(30);
      mgr.getASPField("CREATE_PERSON").setValidation("ITEM0_PERSON_NAME");
      mat_arrive_line_blk.setView("MAT_ARRIVE_LINE");
      mat_arrive_line_blk.defineCommand("MAT_ARRIVE_LINE_API","New__,Modify__,Remove__");
      mat_arrive_line_blk.setMasterBlock(headblk);
      mat_arrive_line_set = mat_arrive_line_blk.getASPRowSet();
      mat_arrive_line_bar = mgr.newASPCommandBar(mat_arrive_line_blk);
      mat_arrive_line_bar.defineCommand(mat_arrive_line_bar.OKFIND, "okFindITEM1");
      mat_arrive_line_bar.defineCommand(mat_arrive_line_bar.NEWROW, "newRowITEM1");
      mat_arrive_line_tbl = mgr.newASPTable(mat_arrive_line_blk);
      mat_arrive_line_tbl.setTitle("MATARRIVELINEITEMHEAD1: MatArriveLine");
      mat_arrive_line_tbl.enableRowSelect();
      mat_arrive_line_tbl.setWrap();
      mat_arrive_line_lay = mat_arrive_line_blk.getASPBlockLayout();
      mat_arrive_line_lay.setDefaultLayoutMode(mat_arrive_line_lay.MULTIROW_LAYOUT);
      mat_arrive_line_lay.setDataSpan("SUPPLIER", 5);
      mat_arrive_line_lay.setDataSpan("PACKAGE_CASE", 5);
      mat_arrive_line_lay.setDataSpan("FRAGILE_DESC", 5);
      mat_arrive_line_lay.setDataSpan("LEFT_PROBLEMS", 5);
      mat_arrive_line_lay.setDataSpan("NOTE", 5);
      mat_arrive_line_lay.setDataSpan("IS_BLOCK_UP", 5);
//      mat_arrive_line_lay.setDataSpan("PACKAGE_CASE", 5);

      mat_arrive_line_lay.setSimple("ITEM_DESC");
      mat_arrive_line_lay.setSimple("ITEM0_PERSON_NAME");
      mat_arrive_line_lay.setSimple("UNIT_DESC");
      mat_arrive_line_lay.setSimple("ITEM0_CONTRACT_DESC");
//      headlay.setSimple("RESPONSE_ORG_DESC");



   }


   public void adjust()
   {
//      super.adjust();
      // fill function body
      if(headset.countRows() > 0&&headlay.isSingleLayout()&&!"已创建".equals(headset.getValue("STATUS"))){
//         headbar.disableCommand(headbar.NEWROW);
         headbar.disableCommand(headbar.EDITROW);
         headbar.disableCommand(headbar.DELETE);
         mat_arrive_line_bar.disableCommand(mat_arrive_line_bar.NEWROW);
         mat_arrive_line_bar.disableCommand(mat_arrive_line_bar.EDITROW);
         mat_arrive_line_bar.disableCommand(mat_arrive_line_bar.DELETE);
//         if("已创建".equals(headset.getValue("STATUS"))) headbar.disableCommand("");
//         if("已创建".equals(headset.getValue("STATUS"))) headbar.disableCommand("");
      }
   }
   
   protected String getImageFieldTag(ASPField imageField, ASPRowSet rowset, int rowNum) throws FndException
   {
      ASPManager mgr = getASPManager();
      String imgSrc = mgr.getASPConfig().getImagesLocation();

      if (rowset.countRows() > 0 && "VIEW_REF_FILE".equals(imageField.getName()))
      {
         if ("TRUE".equals(rowset.getValueAt(rowNum, "EXIST_DOC_REF"))) {
            imgSrc += "folder.gif";
            return "<img src=\"" + imgSrc + "\" height=\"16\" width=\"16\" border=\"0\">";
         }
         else
         {
            return "";
         }
      }
      return "";
   }

   public void makeAccept(){
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      int headrowno;
      cmd = trans.addCustomCommand("PROJ_NO,ARRIVE_ID","MAT_ARRIVE_API.Make_Accept___");
      cmd.setParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ARRIVE_ID", headset.getValue("ARRIVE_ID"));
      trans = mgr.perform(trans);
      cmd.clear();
      headrowno=headset.getCurrentRowNo();
      okFind();
      headset.goTo(headrowno);
   }
   

   public void makeClose(){
      ASPManager mgr = getASPManager();
      ASPTransactionBuffer trans = mgr.newASPTransactionBuffer();
      ASPCommand cmd;
      int headrowno;
      cmd = trans.addCustomCommand("PROJ_NO,ARRIVE_ID","MAT_ARRIVE_API.Make_Close___");
      cmd.setParameter("PROJ_NO", headset.getValue("PROJ_NO"));
      cmd.setParameter("ARRIVE_ID", headset.getValue("ARRIVE_ID"));
      trans = mgr.perform(trans);
      cmd.clear();
      headrowno=headset.getCurrentRowNo();
      okFind();
      headset.goTo(headrowno);
   }
   

   public void  printReport() throws FndException, UnsupportedEncodingException
  {
   ASPManager mgr = getASPManager();
   ASPConfig cfg = getASPConfig();
   String URL=cfg.getParameter("APPLICATION/RUNQIAN/SERVER_URL");
   if (headlay.isMultirowLayout())
      headset.goTo(headset.getRowSelected());
   if (headset.countRows()>0 )
         {   
            String proj_no = headset.getValue("PROJ_NO");
            String arrive_id = headset.getValue("ARRIVE_ID");
             appendDirtyJavaScript("window.open('"+URL+"/showReport.jsp?raq=MatArrive.raq&proj_no="+proj_no+"&arrive_id="+arrive_id
               + "','_blank','height=600, width=780, top=200, left=350, toolbar=no, menubar=no, scrollbars=yes, resizable=yes,location=no, status=no');");                                
        }
  }   

   //-----------------------------------------------------------------------------
   //------------------------  Presentation functions  ---------------------------
   //-----------------------------------------------------------------------------

   protected String getDescription()
   {
      return "MATARRIVEDESC: Mat Arrive";
   }


   protected String getTitle()
   {
      return "MATARRIVETITLE: Mat Arrive";
   }


   protected void printContents() throws FndException
   {
      super.printContents();

      ASPManager mgr = getASPManager();
      if (headlay.isVisible())
          appendToHTML(headlay.show());
      else
      {
         headlay.setLayoutMode(headlay.CUSTOM_LAYOUT);
         appendToHTML(headlay.show());
      }
      if (mat_arrive_line_lay.isVisible())
          appendToHTML(mat_arrive_line_lay.show());
   }
   //--------------------------  Added in new template  --------------------------
   //--------------  Return blk connected with workflow functions  ---------------
   //-----------------------------------------------------------------------------

   protected ASPBlock getBizWfBlock()
   {
      return headblk;
   }
}
